/*
 * Wazuh auth middleware (framework-agnostic)
 * Copyright (C) 2015, Wazuh Inc.
 * July 20, 2026.
 *
 * This program is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General Public
 * License (version 2) as published by the FSF - Free Software
 * Foundation.
 */

#pragma once

#include <mutex>
#include <string>
#include <unordered_map>

#include "iAgentKeystore.hpp"

namespace remoted::auth
{

    /**
     * @brief IAgentKeystore backed by a direct read of client.keys.
     *
     * Parses the manager's client.keys file the same way the manager's own
     * OS_ReadKeys() does (shared/os_crypto/shared/keys.c): each line is
     * "id name ip key"; lines starting with '#' or ' ' are comments; an
     * entry whose name field starts with '#' or '!' is a removed/disabled
     * agent and is skipped, exactly like OS_ReadKeys() discards it.
     *
     * It is independent of remoted's own C keystore: it reads the file
     * itself and keeps its own in-memory copy, so it never touches
     * remoted's `keystore`/`keyentry` types. That also means it does not
     * see the `encryption_key` remoted derives from `W_ENCRYPTION_KEY` mode
     * -- it works directly off the key column, as written on disk.
     *
     * The key column is expected to be lowercase hex (as generated by
     * manage_agents/authd); it is hex-decoded into raw bytes and used as-is,
     * with no further derivation. It must decode to 16, 24 or 32 bytes to be
     * usable as an AES-CMAC key; AuthMiddleware reports AuthError::MissingKey
     * for an agent whose key does not (see keyFor()).
     */
    class Keystore : public IAgentKeystore
    {
    public:
        /// Path to client.keys, relative to the manager's home directory.
        static constexpr const char* kDefaultPath = "etc/client.keys";

        /**
         * @param path Path to client.keys. Loaded immediately; a missing or
         *             unreadable file is not an error -- the keystore just
         *             starts empty (see reload()).
         */
        explicit Keystore(std::string path = kDefaultPath);

        /**
         * @brief Re-read client.keys from disk, replacing the in-memory copy.
         *
         * Not called automatically on any schedule; the caller decides when
         * a re-read is warranted (e.g. after enrollment/removal).
         *
         * @return Number of agent keys loaded, or -1 if the file could not be opened.
         */
        int reload();

        /**
         * @brief Look up an agent's key in the in-memory copy of client.keys.
         *
         * @param agentId Agent id, as it appears in client.keys' first column.
         * @return std::nullopt if the id is not present (including removed/disabled
         *         entries, which are never loaded). Otherwise the agent's key,
         *         empty if the on-disk key column failed to hex-decode.
         */
        std::optional<std::vector<std::uint8_t>> keyFor(const std::string& agentId) const override;

    private:
        std::string m_path;
        mutable std::mutex m_mutex;
        std::unordered_map<std::string, std::vector<std::uint8_t>> m_keys;
    };

} // namespace remoted::auth
