/*
 * Wazuh auth middleware (framework-agnostic)
 * Copyright (C) 2015, Wazuh Inc.
 * July 20, 2026.
 *
 * This program is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General Public
 * License (version 2) as published by the FSF - Free Software
 * Foundation.
 */

#pragma once

#include <atomic>
#include <cstdint>
#include <mutex>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#include "addressRule.hpp"        // Value type only; pulls no I/O headers.
#include "common/logThrottle.hpp" // Safe in a header: LogThrottle deliberately does not log.
#include "iAgentKeystore.hpp"

namespace remoted::auth
{

    /**
     * @brief IAgentKeystore backed by a direct read of client.keys, hot-reloaded on change.
     *
     * Parses the manager's client.keys file the same way the manager's own
     * OS_ReadKeys() does (shared/os_crypto/shared/keys.c): each line is
     * "id name ip key"; lines starting with '#' or ' ' are comments; an
     * entry whose name field starts with '#' or '!' is a removed/disabled
     * agent and is skipped, exactly like OS_ReadKeys() discards it. The id
     * column must parse as AgentId (a non-negative integer, fully consuming
     * the field); a non-numeric id is likewise skipped (see reload()) -- an
     * agent id is always numeric by design, so that line can never match a
     * real lookup anyway.
     *
     * It is independent of remoted's own C keystore: it reads the file
     * itself and keeps its own in-memory copy, so it never touches
     * remoted's `keystore`/`keyentry` types. That also means it does not
     * see the `encryption_key` remoted derives from `W_ENCRYPTION_KEY` mode
     * -- it works directly off the key column, as written on disk.
     *
     * The key column is expected to be 64 lowercase hex chars (as generated by
     * manage_agents/authd); it is hex-decoded into the 32 raw bytes of the
     * agent's HS256 key and used as-is, with no further derivation. Anything
     * else is unusable; AuthMiddleware reports AuthError::MissingKey for an
     * agent whose key does not decode (see lookup()).
     *
     * The ip column is parsed into an AddressRule and enforced through
     * lookup(), replicating the legacy remoted's own check so one
     * client.keys authorizes the same peers on both pipelines. A line whose ip
     * column does not parse is skipped, like the other malformed-line cases
     * above -- it is not fatal to the load (see reload()).
     *
     * Hot-reload: a background thread watches the file (inotify, with a
     * periodic fallback poll -- see the classic pipeline's equivalent,
     * rem_keyupdate_main in src/remoted/src/secure.c) and calls reload()
     * whenever the file's content hash looks different from the last
     * successful load (mtime is only second-granularity, so two rewrites in
     * the same second can't be told apart by timestamp alone). The watcher is
     * fully RAII: started at the end of the constructor, stopped and joined in
     * the destructor
     */
    class Keystore : public IAgentKeystore
    {
    public:
        /// Path to client.keys, relative to the manager's home directory.
        static constexpr const char* kDefaultPath = "etc/client.keys";

        /// Built-in refresh interval when the caller passes <=0 (matches remoted.keyupdate_interval's
        /// own built-in default in the legacy pipeline).
        static constexpr int kDefaultRefreshIntervalSeconds = 10;

        /**
         * @param path Path to client.keys. Loaded immediately; a missing or
         *             unreadable file is not an error -- the keystore just
         *             starts empty (see reload()).
         * @param refreshIntervalSeconds How often the background watcher re-checks the file as a
         *             fallback to the inotify subscription (seconds). <=0 -> kDefaultRefreshIntervalSeconds.
         */
        explicit Keystore(std::string path = kDefaultPath, int refreshIntervalSeconds = kDefaultRefreshIntervalSeconds);

        ~Keystore() override;

        Keystore(const Keystore&) = delete;
        Keystore& operator=(const Keystore&) = delete;

        /**
         * @brief Re-read client.keys from disk, replacing the in-memory copy.
         *
         * Always re-parses the file when called (the background watcher decides
         * separately whether calling this is warranted -- see the class comment).
         * Guarded against a concurrent rewrite: the file's content hash is captured
         * before and after parsing, and the parse is retried (a few times, briefly)
         * if they don't match, so a line caught mid-write is never adopted into the
         * in-memory table. Safe to call from multiple threads (serialized internally).
         *
         * @return Number of agent keys loaded, or -1 if the file could not be
         *         opened, or if the file kept changing across every retry attempt
         *         (in which case the previous in-memory table is left untouched).
         */
        int reload();

        /// reload() failure reasons. Distinguished because they need different operator messages:
        /// an unreadable file is an install/permissions problem the caller must report, while an
        /// unstable one is transient and already reported by reload() itself.
        static constexpr int kReloadUnreadable {-1}; ///< Missing, unreadable, or permission-denied.
        static constexpr int kReloadUnstable {-2};   ///< Kept changing across every read attempt.

        /**
         * @brief Look up an agent in the in-memory copy of client.keys.
         *
         * @param agentId Agent id, as it appears (numerically) in client.keys' first column.
         * @param peerIp  Textual peer address as observed on the socket.
         * @return std::nullopt if the id is not present (including removed/disabled entries, entries
         *         whose id column isn't numeric, and entries whose ip column didn't parse -- see
         *         reload()). Otherwise the agent's key, empty if the key column failed to hex-decode,
         *         plus whether @p peerIp satisfies the ip column.
         */
        std::optional<AgentLookup> lookup(AgentId agentId, std::string_view peerIp) const override;

        // Health counters behind the remoted.auth.keystore.* pull metrics (registered by the
        // facade -- this class stays metrics-library-free, the same constraint that keeps
        // loggerHelper.h out of this header). Plain relaxed atomics: reload() maintains them,
        // any thread may read them at dump cadence.

        /// @brief Agents with a usable key after the last SUCCESSFUL reload (reload()'s return).
        std::size_t agentsLoaded() const noexcept
        {
            return m_agentsLoaded.load(std::memory_order_relaxed);
        }

        /// @brief Successful reloads since construction (startup load included).
        /**
         * @brief client.keys lines the last adopted load could not use.
         *
         * A level, like agentsLoaded(): it describes the file as it stands now, which is the
         * question an operator asks ("is my client.keys healthy?"). Counts the unusable lines --
         * fewer than four fields, a non-numeric id, an ip column that does not parse, and a key
         * column that does not decode -- and deliberately NOT comments, blanks or entries marked
         * as removed, which are normal states rather than defects. Each one is also logged.
         */
        std::size_t entriesSkipped() const noexcept
        {
            return m_entriesSkipped.load(std::memory_order_relaxed);
        }

        std::uint64_t reloadsTotal() const noexcept
        {
            return m_reloadsTotal.load(std::memory_order_relaxed);
        }

        /// @brief Failed reloads since construction (unreadable file or torn-read give-up).
        std::uint64_t reloadFailuresTotal() const noexcept
        {
            return m_reloadFailuresTotal.load(std::memory_order_relaxed);
        }

    private:
        /// One client.keys line's worth of state.
        struct AgentEntry
        {
            /// The 32 raw HS256 key bytes; empty when the key column did not decode to exactly that --
            /// the distinction that lets AuthMiddleware answer MissingKey instead of UnknownAgent.
            std::vector<std::uint8_t> key;
            /// Parsed ip column. Always present: a line whose column failed to parse is not loaded.
            AddressRule address;
        };

        /// Watcher thread entry point: an exception barrier around watcherLoopBody(). A throw
        /// escaping a bare std::thread would terminate the whole remoted daemon.
        void watcherLoop();

        /// The actual inotify + poll() loop, see keystore.cpp for the full design.
        void watcherLoopBody();

        /// Closes the inotify/eventfd descriptors and resets them to -1. Idempotent; used both by
        /// the destructor and by the constructor's rollback path (a constructor that throws never
        /// runs the destructor, so the descriptors would otherwise leak).
        void closeWatchFds() noexcept;

        /// Drains every pending inotify event on m_inotifyFd (it's non-blocking) and, if any of
        /// them invalidated the watch (IN_IGNORED/IN_MOVE_SELF/IN_DELETE_SELF -- typical of an
        /// atomic rename-replace of the file), re-adds it on the same path.
        void drainInotifyEvents();

        /// Gate run by the watcher before considering a reload: true if the file's content hash
        /// looks different from the last successful reload (or reload() was never called yet),
        /// false if nothing has changed (or the file is transiently unreachable). Guarded by
        /// m_reloadMutex, same as reload() itself -- see that field's comment.
        bool fileLooksChanged();

        std::string m_path;
        mutable std::mutex m_mutex;
        std::unordered_map<AgentId, AgentEntry> m_keys;

        // Hot-reload: background watcher (inotify + periodic fallback poll via poll()'s timeout).
        int m_refreshIntervalSeconds;
        int m_inotifyFd {-1};
        int m_watchDescriptor {-1};
        int m_stopEventFd {-1}; ///< Written by the destructor for an immediate cooperative wakeup.
        std::thread m_watcherThread;

        /// Fallback stop signal, checked every loop iteration independent of m_stopEventFd: if
        /// eventfd() failed at construction (m_stopEventFd stays -1), poll() has no fd to wake it
        /// early, but this flag still gets noticed the next time poll()'s own timeout elapses (at
        /// most m_refreshIntervalSeconds later) -- so the watcher thread is always joinable within
        /// a bounded time, never permanently, which the destructor's join() would otherwise wait
        /// on forever.
        std::atomic<bool> m_stopping {false};

        // Serializes reload() (so at most one parse runs at a time, whether triggered by the
        // watcher or called directly) and guards the last-known content hash below, which
        // fileLooksChanged() reads and reload() updates on success. Content hash, not mtime/size:
        // two rewrites landing in the same wall-clock second (mtime is second-granularity) can
        // otherwise look identical despite different content.
        std::mutex m_reloadMutex;
        bool m_hasBaseline {false};
        std::vector<std::uint8_t> m_lastHash;

        /// Throttles the "client.keys is unreadable" warning: the watcher retries every
        /// m_refreshIntervalSeconds, so an unreadable file would otherwise flood wazuh-manager.log .
        remoted::common::LogThrottle m_unreadableThrottle;

        // See the public accessors; maintained exclusively by reload().
        std::atomic<std::size_t> m_agentsLoaded {0};
        std::atomic<std::size_t> m_entriesSkipped {0};
        std::atomic<std::uint64_t> m_reloadsTotal {0};
        std::atomic<std::uint64_t> m_reloadFailuresTotal {0};
    };

} // namespace remoted::auth
