# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false # don't auto-update the guest additions
    end

    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
    end

    config.vm.define :engine do |engine|
        engine.vm.box = "msi/ubuntu-jammy"
        engine.vm.network :private_network, ip: "10.0.0.28"
        engine.vm.hostname = "vm-engine"
        engine.ssh.username = 'vagrant'
        engine.ssh.password = 'vagrant'
        engine.ssh.insert_key = 'true'
        engine.vm.synced_folder "./engine", "/vagrant"
        engine.vm.provider "virtualbox" do |pmv|
        pmv.memory = 6144
        pmv.cpus   = 6
        engine.vm.provision "shell", inline: <<-SHELL
        #Dependencies
        sudo apt-get update
        sudo apt-get install gcc g++ make libc6-dev curl policycoreutils automake autoconf gnupg apt-transport-https libtool libssl-dev -y

        #CMake 3.24 installation from sources
        sudo apt-get install libssl-dev libcurl4-gnutls-dev
        sudo apt-get install cmake

        #Download the Wazuh installation assistant.
        curl -sO https://packages.wazuh.com/4.3/wazuh-install.sh
        curl -sO https://packages.wazuh.com/4.3/config.yml
        sed -E -i 's/ ip: <indexer-node-ip>/ ip: 192.168.56.28/gm' config.yml
        sed -E -i 's/ ip: <wazuh-manager-ip>/ ip: 192.168.56.28/gm' config.yml
        sed -E -i 's/ ip: <dashboard-node-ip>/ ip: 192.168.56.28/gm' config.yml
        sudo bash wazuh-install.sh --generate-config-files
        sudo bash wazuh-install.sh -a

        # filebeat & elastic
        # Change manifest.yml (/usr/share/filebeat/module/wazuh/alerts/manifest.yml)
        sudo curl -o /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/14738-filebeat-  mappings-ecs-engine/src/engine/extension/elasticsearch/7.x/wazuh-template.json
        sudo systemctl restart wazuh-indexer
        sudo systemctl restart filebeat.service

        #Download engine
        mkdir engine &&	cd engine
        git clone https://github.com/wazuh/wazuh.git
        cd wazuh && git checkout 11334-dev-new-wazuh-engine
        cd src/engine && mkdir build
        cmake -S . -B build/
        /usr/local/bin/cmake --build build/ --config Debug --target main -j 2

        #Remplace engine for analysisd
        rm /var/ossec/queue/sockets/queue #Remove queue of Analysisd
        rm /var/ossec/queue/sockets/queue #Remove queue
        build/main start --event_endpoint /var/ossec/queue/sockets/queue --api_endpoint /var/ossec/queue/sockets/engine-api --threads 1 --file_storage /var/ossec/engine/store </dev/null &>/dev/null & # Inicialize engine
        build/main catalog -e /var/ossec/queue/sockets/engine-api -y load decoder ruleset/decoders/
        build/main catalog -e /var/ossec/queue/sockets/engine-api -y load output ruleset/outputs/
        build/main catalog -e /var/ossec/queue/sockets/engine-api -y load environment ruleset/environments/
        build./main env -e /var/ossec/queue/sockets/engine-api set environment/wazuh/0.1
        sudo chown wazuh /var/ossec/queue/
        sudo chmod 660 /var/ossec/queue/
        sudo pkill -e analysisd #Kill analysisd

        SHELL
        end
    end

  end
