# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import api_communication.proto.engine_pb2 as _engine_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstatus.proto\x12\x1b\x63om.wazuh.api.engine.status\x1a\x0c\x65ngine.proto\"\x13\n\x11StatusGet_Request\"n\n\nSpaceState\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0c\n\x04hash\x18\x04 \x01(\t\x12\x1e\n\x16last_successful_update\x18\x05 \x01(\r\"`\n\rResourceState\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12\x1e\n\x16last_successful_update\x18\x04 \x01(\r\"\xd8\x04\n\x12StatusGet_Response\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".com.wazuh.api.engine.ReturnStatus\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\r\n\x05ready\x18\x03 \x01(\x08\x12K\n\x06spaces\x18\x04 \x03(\x0b\x32;.com.wazuh.api.engine.status.StatusGet_Response.SpacesEntry\x12\x45\n\x03ioc\x18\x05 \x03(\x0b\x32\x38.com.wazuh.api.engine.status.StatusGet_Response.IocEntry\x12\x45\n\x03geo\x18\x06 \x03(\x0b\x32\x38.com.wazuh.api.engine.status.StatusGet_Response.GeoEntry\x1aV\n\x0bSpacesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.com.wazuh.api.engine.status.SpaceState:\x02\x38\x01\x1aV\n\x08IocEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.com.wazuh.api.engine.status.ResourceState:\x02\x38\x01\x1aV\n\x08GeoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x39\n\x05value\x18\x02 \x01(\x0b\x32*.com.wazuh.api.engine.status.ResourceState:\x02\x38\x01\x42\x08\n\x06_errorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSGET_RESPONSE_SPACESENTRY._options = None
  _STATUSGET_RESPONSE_SPACESENTRY._serialized_options = b'8\001'
  _STATUSGET_RESPONSE_IOCENTRY._options = None
  _STATUSGET_RESPONSE_IOCENTRY._serialized_options = b'8\001'
  _STATUSGET_RESPONSE_GEOENTRY._options = None
  _STATUSGET_RESPONSE_GEOENTRY._serialized_options = b'8\001'
  _STATUSGET_REQUEST._serialized_start=59
  _STATUSGET_REQUEST._serialized_end=78
  _SPACESTATE._serialized_start=80
  _SPACESTATE._serialized_end=190
  _RESOURCESTATE._serialized_start=192
  _RESOURCESTATE._serialized_end=288
  _STATUSGET_RESPONSE._serialized_start=291
  _STATUSGET_RESPONSE._serialized_end=891
  _STATUSGET_RESPONSE_SPACESENTRY._serialized_start=619
  _STATUSGET_RESPONSE_SPACESENTRY._serialized_end=705
  _STATUSGET_RESPONSE_IOCENTRY._serialized_start=707
  _STATUSGET_RESPONSE_IOCENTRY._serialized_end=793
  _STATUSGET_RESPONSE_GEOENTRY._serialized_start=795
  _STATUSGET_RESPONSE_GEOENTRY._serialized_end=881
# @@protoc_insertion_point(module_scope)
