# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api.models.agent_deleted import AgentDeleted  # noqa: F401,E501
from api.models.api_response import ApiResponse  # noqa: F401,E501
from api import util


class AgentDeletedData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error: int=None, message: str=None, data: AgentDeleted=None):  # noqa: E501
        """AgentDeletedData - a model defined in Swagger

        :param error: The error of this AgentDeletedData.  # noqa: E501
        :type error: int
        :param message: The message of this AgentDeletedData.  # noqa: E501
        :type message: str
        :param data: The data of this AgentDeletedData.  # noqa: E501
        :type data: AgentDeleted
        """
        self.swagger_types = {
            'error': int,
            'message': str,
            'data': AgentDeleted
        }

        self.attribute_map = {
            'error': 'error',
            'message': 'message',
            'data': 'data'
        }

        self._error = error
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'AgentDeletedData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AgentDeletedData of this AgentDeletedData.  # noqa: E501
        :rtype: AgentDeletedData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> int:
        """Gets the error of this AgentDeletedData.


        :return: The error of this AgentDeletedData.
        :rtype: int
        """
        return self._error

    @error.setter
    def error(self, error: int):
        """Sets the error of this AgentDeletedData.


        :param error: The error of this AgentDeletedData.
        :type error: int
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def message(self) -> str:
        """Gets the message of this AgentDeletedData.


        :return: The message of this AgentDeletedData.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this AgentDeletedData.


        :param message: The message of this AgentDeletedData.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> AgentDeleted:
        """Gets the data of this AgentDeletedData.


        :return: The data of this AgentDeletedData.
        :rtype: AgentDeleted
        """
        return self._data

    @data.setter
    def data(self, data: AgentDeleted):
        """Sets the data of this AgentDeletedData.


        :param data: The data of this AgentDeletedData.
        :type data: AgentDeleted
        """

        self._data = data
