# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api.models.agent_deleted import AgentDeleted  # noqa: F401,E501
from api.models.api_response import ApiResponse  # noqa: F401,E501
from api import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, api_response: ApiResponse=None, data: AgentDeleted=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param api_response: The api_response of this InlineResponse2001.  # noqa: E501
        :type api_response: ApiResponse
        :param data: The data of this InlineResponse2001.  # noqa: E501
        :type data: AgentDeleted
        """
        self.swagger_types = {
            'api_response': ApiResponse,
            'data': AgentDeleted
        }

        self.attribute_map = {
            'api_response': 'ApiResponse',
            'data': 'data'
        }

        self._api_response = api_response
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_response(self) -> ApiResponse:
        """Gets the api_response of this InlineResponse2001.


        :return: The api_response of this InlineResponse2001.
        :rtype: ApiResponse
        """
        return self._api_response

    @api_response.setter
    def api_response(self, api_response: ApiResponse):
        """Sets the api_response of this InlineResponse2001.


        :param api_response: The api_response of this InlineResponse2001.
        :type api_response: ApiResponse
        """

        self._api_response = api_response

    @property
    def data(self) -> AgentDeleted:
        """Gets the data of this InlineResponse2001.


        :return: The data of this InlineResponse2001.
        :rtype: AgentDeleted
        """
        return self._data

    @data.setter
    def data(self, data: AgentDeleted):
        """Sets the data of this InlineResponse2001.


        :param data: The data of this InlineResponse2001.
        :type data: AgentDeleted
        """

        self._data = data
