@startuml
actor "wmodules-thread" as wmodules
actor "receiver-thread" as recv
actor "send-queue" as queue
participant syscollector as sysco
participant dbsync
participant rsync
participant normalizer
participant sysinfo
activate sysinfo

wmodules -> sysco : instance()
activate sysco
wmodules -> sysco : init()
sysco -> dbsync : create()
activate dbsync
sysco -> rsync : create()
activate rsync
sysco -> normalizer : create()
activate normalizer
sysco -> sysco : registerWithRsync()
sysco -> rsync : registerSyncID()
note right
will register each enabled scan 
end note

group syncLoop()
    alt scan_on_start
        sysco -> sysco : scan() ...
        sysco -> sysco : sync() ...
    end
    loop !stopping
        sysco -> sysco : scan()
            activate sysco
            sysco -> sysco : scanHardware()
                activate sysco #LightBlue
                sysco -> sysinfo : hardware()
                sysinfo --> sysco : hwData
                sysco -> dbsync : syncTxnRow(hwData)
                dbsync -> sysco : reportDiffFunction()
                activate sysco
                sysco ->x queue : sendDiffToManager()
                sysco --> dbsync
                deactivate sysco
                sysco -> dbsync : getDeletedRows()
                deactivate sysco
            sysco -> sysco : syncHardware()
            deactivate sysco

            ' sysco -> sysco : scanOs()
            ' sysco -> sysco : scanNetwork()
            ' sysco -> sysco : scanPackages()
            ' sysco -> sysco : scanPorts()
            ' sysco -> sysco : scanProcesses()
        group sync()
            sysco -> sysco : syncHardware()
            ' sysco -> sysco : syncOs()
            ' sysco -> sysco : syncNetwork()
            ' sysco -> sysco : syncPackages()
            ' sysco -> sysco : syncPorts()
            ' sysco -> sysco : syncProcesses()
        end
    sysco -> sysco : sleep(intervalValue)
    end
end


recv -> sysco : push_message(string)
alt !stopping
    sysco -> rsync : pushMessage(vector)
    note right
        std::string is copied into a
        std::vector<uint8_t> to be passed to rsync.
    end note
end
@enduml