@startuml hardware
actor "send-queue" as queue
participant syscollector as sysco
participant sysinfo
participant dbsync
participant rsync

activate dbsync
activate rsync
activate sysco
activate sysinfo
== Scan ==
sysco -> sysco++ : scan()
sysco -> sysco++ : scanHardware()
alt hardware enabled
    sysco -> sysco++ : getHardwareData()
        sysco -> sysinfo : hardware()
        sysco <-- sysinfo : hardwareData
        sysco -> sysco : hardwareData["checksum"] = getItemChecksum(hardwareData)
    sysco--
    sysco -> sysco++ : updateAndNotifyChanges()
        sysco -> dbsync : createTxn()
        sysco <-- dbsync : txn
        sysco -> dbsync++ : txn.syncTxnRow()
            alt new
                dbsync -> sysco : notify(Inserted)
            else modified
                dbsync -> sysco : notify(Modified)
            end
            sysco ->x queue : sendDiff()
            dbsync <-- sysco
            dbsync --> sysco
        dbsync--
        sysco -> dbsync++ : txn.getDeletedRows()
            dbsync -> sysco : notify(Deleted)
            sysco ->x queue : sendDiff()
            dbsync <-- sysco
            dbsync --> sysco
        dbsync--
    sysco--
end
sysco--
sysco--
== Sync ==
sysco -> sysco++ : sync()
sysco -> sysco++ : syncHardware()
    alt hardware enabled
        sysco -> dbsync : handle()
        sysco <-- dbsync : handle
        sysco -> rsync++ : startSync(handle)
            rsync -> dbsync : selectRows()
            dbsync --> rsync : rows
            rsync -> rsync : buildSyncMessage(rows)
            rsync -> sysco : notifySync()
            sysco -> queue : sendSync()
            sysco <-- queue
            sysco --> rsync
            rsync --> sysco
        rsync--
    end
sysco--
sysco--

@enduml

