@startuml
actor "send-queue" as queue
participant syscollector as sysco
participant sysinfo
participant dbsync
participant rsync

activate dbsync
activate rsync
activate sysco
activate sysinfo
== Scan ==
sysco -> sysco++ : scan()
sysco -> sysco++ : scanPorts()
alt ports enabled
    sysco -> sysco++ : getPortsData()
        sysco -> sysinfo : ports()
        sysco <-- sysinfo : data
        loop for each port
            alt port.type = TCP
                alt all ports enabled
                    sysco -> sysco : getItemId()
                    sysco -> sysco : isElementDuplicated()
                    alt not duplicated
                        sysco -> sysco : ret.pus_back()
                    end
                else port.state = Listening
                    sysco -> sysco : getItemId()
                    sysco -> sysco : isElementDuplicated()
                    alt not duplicated
                        sysco -> sysco : ret.pus_back()
                    end
                end
            else port.type = UDP
                sysco -> sysco : getItemId()
                sysco -> sysco : isElementDuplicated()
                alt not duplicated
                    sysco -> sysco : ret.pus_back()
                end
            end
        end
    sysco--
    sysco -> sysco++ : updateAndNotifyChanges()
        sysco -> dbsync : createTxn()
        sysco <-- dbsync : txn
        sysco -> dbsync++ : txn.syncTxnRow()
            alt new
                dbsync -> sysco : notify(Inserted)
            else modified
                dbsync -> sysco : notify(Modified)
            end
            sysco ->x queue : sendDiff()
            dbsync <-- sysco
            dbsync --> sysco
        dbsync--
        sysco -> dbsync++ : txn.getDeletedRows()
            dbsync -> sysco : notify(Deleted)
            sysco ->x queue : sendDiff()
            dbsync <-- sysco
            dbsync --> sysco
        dbsync--
    sysco--
end
sysco--
sysco--
== Sync ==
sysco -> sysco++ : sync()
sysco -> sysco++ : syncPorts()
    alt ports enabled
        sysco -> dbsync : handle()
        sysco <-- dbsync : handle
        sysco -> rsync++ : startSync(handle)
            rsync -> dbsync : selectRows()
            dbsync --> rsync : rows
            rsync -> rsync : buildSyncMessage(rows)
            rsync -> sysco : notifySync()
            sysco -> queue : sendSync()
            sysco <-- queue
            sysco --> rsync
            rsync --> sysco
        rsync--
    end
sysco--
sysco--

@enduml