@startuml
participant  SysInfo               as dataprovider
collections  RegistriesWindows     as registry
participant  FactoryWindowsPackage as packages
participant  AppxStorePackages     as appstoreclass

dataprovider -> registry                          : Get IDs user from HKEY_USERS
loop Iterate users

    == Initialization ==

    dataprovider -> registry                      : Get sub-registries store packages from cache
    note left
        (HKEY_USERS\<userID>\SOFTWARE\Classes\Local Settings\MrtCache)
    end note
    dataprovider -> registry                      : Get sub-registries of store packages
    note left
        (HKEY_USERS\<userID>\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages)
    end note

    == Getting data ==

    loop Iterate package

        dataprovider -> packages                  : Get package information
        dataprovider -> packages                  : Request packages information

        packages -> appstoreclass ++              : GetVersion()
        note right
            Sub-registry name format
            <VendorID>.<FullNameApp>_<Version>_<Architecture>_<UUID>
            HKEY_USERS\<userID>\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\<sub-registry>
        end note
        appstoreclass --> packages --             : Version

        packages -> appstoreclass ++              : GetArchitecture()
        note right
            Sub-registry name format
            <VendorID>.<FullNameApp>_<Version>_<Architecture>_<UUID>
            HKEY_USERS\<userID>\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\<sub-registry>
        end note
        appstoreclass --> packages --             : Architecture

        packages -> appstoreclass ++              : GetLocation()
        note right
            Read PackageRoot field in sub-registry application
            (HKEY_USERS\<userID>\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\<sub-registry>)
        end note
        appstoreclass --> packages --             : Location

        packages -> appstoreclass ++              : GetName()
        appstoreclass <-> registry                : Get name app for main registry
        note right
            Get name from ApplicationName field
            (HKEY_USERS\<userID>\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\<package-registry>\<sub-registry>\Capabilities)
        end note
        alt start with "@{"
            appstoreclass <-> registry            : Get name from cache registry
            note right
                Key looking for will be the value obtained before.
                (HKEY_USERS\<UserID>\SOFTWARE\\Classes\\Local Settings\\MrtCache\<name-App>\<sub-registry>\<sub-registry>
            end note
        end
        appstoreclass --> packages --             : Name

        packages -> appstoreclass ++              : GetVendor()
        appstoreclass -> registry                 : Get name registries with vendor name value
        note right
            Get the name of the registry that has the package name
            (HKEY_USERS\<userID>\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\<package-registry>\<sub-registry>\Capabilities\FileAssociations)
            (HKEY_USERS\<userID>\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\<package-registry>\<sub-registry>\Capabilities\URLAssociations)
        end note
        appstoreclass <-> registry                : Get name vendor
        note right
            (HKEY_USERS\<userID>\SOFTWARE\Classes\<Registry>\Application)
        end note
        appstoreclass --> packages --             : Vendor

        packages --> dataprovider                 : Returns package information

    end
end
@enduml
