' Copyright (C) 2015-2021, Wazuh Inc.
' Created by Wazuh, Inc. <info@wazuh.com>.
' This program is free software; you can redistribute it and/or modify it under the terms of GPLv2

@startuml processes
actor "send-queue" as queue
participant syscollector as sysco
participant sysinfo
participant dbsync
participant rsync

activate dbsync
activate rsync
activate sysco
activate sysinfo
== Scan ==
sysco -> sysco++ : scan()
sysco -> sysco++ : scanProcesses()
alt processes enabled
    sysco -> sysco++ : getProcessesData()
        sysco -> sysinfo : processes()
        sysco <-- sysinfo : processesData
        loop for each process in processesData
                sysco -> sysco : process["checksum"] = getItemChecksum(process)
                sysco -> sysco : ret.push_back(process)
        end
    sysco--
    sysco -> sysco++ : updateAndNotifyChanges()
        sysco -> dbsync : createTxn()
        sysco <-- dbsync : txn
        sysco -> dbsync++ : txn.syncTxnRow()
            alt new
                dbsync -> sysco : notify(Inserted)
            else modified
                dbsync -> sysco : notify(Modified)
            end
            sysco ->x queue : sendDiff()
            dbsync <-- sysco
            dbsync --> sysco
        dbsync--
        sysco -> dbsync++ : txn.getDeletedRows()
            dbsync -> sysco : notify(Deleted)
            sysco ->x queue : sendDiff()
            dbsync <-- sysco
            dbsync --> sysco
        dbsync--
    sysco--
end
sysco--
sysco--
== Sync ==
sysco -> sysco++ : sync()
sysco -> sysco++ : syncProcesses()
    alt processes enabled
        sysco -> dbsync : handle()
        sysco <-- dbsync : handle
        sysco -> rsync++ : startSync(handle)
            rsync -> dbsync : selectRows()
            dbsync --> rsync : rows
            rsync -> rsync : buildSyncMessage(rows)
            rsync -> sysco : notifySync()
            sysco -> queue : sendSync()
            sysco <-- queue
            sysco --> rsync
            rsync --> sysco
        rsync--
    end
sysco--
sysco--

@enduml

