/* Copyright (C) 2015, Wazuh Inc.
 * Copyright (C) 2009 Trend Micro Inc.
 * All rights reserved.
 *
 * This program is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General Public
 * License (version 2) as published by the FSF - Free Software
 * Foundation.
 */

#ifndef MANAGE_AGENTS_H
#define MANAGE_AGENTS_H

#include "shared.h"
#include "sec.h"
#include <cJSON.h>

#ifndef ARGV0
#define ARGV0 "manage_agents"
#endif

/** Prototypes **/

/* Read any input from the user (stdin) */
char *read_from_user(void);

/* Import a key */
int k_import(const char *cmdimport);

/**
 * @brief Converts invalid hostnames to valid by eliminating
 * invalid characters
 *
 * @param u_name name to be converted
 * */
void OS_ConvertToValidAgentName(char *u_name);

/* Validation functions */
int OS_IsValidName(const char *u_name);
int OS_IsValidID(const char *id);
int IDExist(const char *id, int discard_removed);
int NameExist(const char *u_name);
char *IPExist(const char *u_ip);
char *getNameById(const char *id);
int OS_AddNewAgent(keystore *keys, const char *id, const char *name, const char *ip, const char *key);
void OS_AddAgentTimestamp(const char *id, const char *name, const char *ip, time_t now);
void OS_RemoveAgentTimestamp(const char *id);
void FormatID(char *id);

/* Print available agents */
int print_agents(int print_status, int active_only, int inactive_only, int csv_output, cJSON *json_output);

/* Clear a line */
char *chomp(char *str);

/* Shared variables */
extern time_t time1;
extern time_t time2;
extern time_t time3;
extern long int rand1;
extern long int rand2;
extern fpos_t fp_pos;
extern char shost[];

/* Internal defines */
#define USER_SIZE       514
#define FILE_SIZE       257
#define STR_SIZE        66
#define VALID_AGENT_NAME_CHARS "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_.-"

/* Internal strings */
#define QUIT                "\\q"
#define AGENT_FILE_DELIMS   ","

/* Print agents */
#define PRINT_AVAILABLE     "\nAvailable agents: \n"
#define PRINT_AGENT         "   ID: %s, Name: %s, IP: %s\n"
#define PRINT_AGENT_STATUS  "   ID: %s, Name: %s, IP: %s, %s\n"

#define PRESS_ENTER     "** Press ENTER to return to the main menu.\n"

#define NO_KEY          "\n** Invalid authentication key. Starting over again.\n"

/* Agent info for import */
#define AGENT_INFO      "Agent information:\n   ID:%s\n   Name:%s\n   " \
                        "IP Address:%s\n\n"
#define ADD_CONFIRM     "Confirm adding it?(y/n): "
#define ADDED           "Added.\n"
#define ADD_NOT         "Not Adding.\n"


/* Import agent */
#define IMPORT_KEY      "\n* Provide the Key generated by the server.\n" \
                        "* The best approach is to cut and paste it.\n" \
                        "*** OBS: Do not include spaces or new lines.\n\n" \
                        "Paste it here (or '\\q' to quit): "


/* Common errors */
#define ERROR_KEYS      "Unable to handle keys file. Exiting.\n"
#define EXTRACT_ERROR   "Unable to extract agent key.\n"
#define INPUT_LARGE     ARGV0 ": Input too large. Not adding it.\n"
#define EXIT            ARGV0 ": Exiting.\n"

#define BANNER          "\n****************************************" \
                        "\n* %s %s Agent manager.%.*s*" \
                        "\n* The following options are available: *" \
                        "\n****************************************\n"


#define BANNER_CLIENT   "   (I)mport key from the server (I).\n" \
                        "   (Q)uit.\n" \
                        "Choose your action: I or Q: "

#endif
