#!/bin/bash

SRC_DIR=`realpath $(dirname "$0")`
OUTPUT_DIR=`realpath $(mktemp -d -t wazuh-rtr-XXXXXX)`
CONTAINER_NAME=wazuh-rtr-engine
RTR_DIR=$SRC_DIR/.rtr
RTR_BIN=rtr.py
RTR_CONFIG="rtr_inputs/rtr_cicd.json"
CURRENT_UID_GID=$(id -u -n):$(id -g -n)
PERMISSIONS_BACKUP_FILE=/tmp/permissions.acl
USERNAME=`logname`
USERID=`id -u $USERNAME`
GROUPID=`id -g $USERNAME`
VERBOSE=''

build() {
    docker build -f .rtr/Dockerfile -t $CONTAINER_NAME .
}

Help() {
    # Display Help
    echo "Run RTR on a directory."
    echo
    echo "Syntax: rtr.sh [-h|o|s|i]"
    echo "options:"
    echo "h     Print this Help."
    echo "o     Output directory."
    echo "s     Source directory."
    echo "i     RTR input file."
    echo "v     Verbose."
    echo
}

run() {
    echo "Running RTR on $SRC_DIR. Output directory: $OUTPUT_DIR. RTR input file: $RTR_CONFIG"
    jq -c '.steps[]' $RTR_CONFIG | while read step
    do
        STEP_DESC=`echo $step | jq -r '.description'`
        STEP_PARAMS=`echo $step | jq -r '.parameters | join(" ")'`
        echo "->Step: $STEP_DESC"
        docker run --rm -v $SRC_DIR:/source -v $OUTPUT_DIR:/output -v $RTR_DIR:/rtr $CONTAINER_NAME /rtr/rtr.py $VERBOSE -u $USERID -g $GROUPID -o /output -s /source $STEP_PARAMS
        docker_exit_code=$?
        if [ $docker_exit_code -ne 0 ]; then
            echo "Execution fail, RTR step: $STEP_DESC"
            exit $docker_exit_code
        fi
    done
    echo "RTR results on $OUTPUT_DIR directory."
}

while getopts ":ho:s:i::v" option
do
    case "${option}" in
        h) # display Help
            Help
            exit;;
        o) # output directory
            OUTPUT_DIR=${OPTARG};;
        s) # source directory
            SRC_DIR=${OPTARG};;
        i) # rtr input file
            RTR_CONFIG=${OPTARG};;
        v) # verbose
            VERBOSE='-v';;
        :) # missing argument
            echo "Error: Missing argument for option $OPTARG"
            exit;;
        \?) # Invalid option
            echo "Error: Invalid option"
            exit;;
    esac
done

#build
run
