#!/bin/bash

SRC_DIR=`realpath $(dirname "$0")`
OUTPUT_DIR=`realpath $(mktemp -d -t wazuh-rtr-XXXXXX)`
CONTAINER_NAME=wazuh-rtr
RTR_DIR=$SRC_DIR/.rtr
RTR_BIN=rtr.py
RTR_CONFIG=rtr_input.json
CURRENT_UID_GID=$(id -u -n):$(id -g -n)
PERMISSIONS_BACKUP_FILE=/tmp/permissions.acl
USERNAME=`logname`
USERID=`id -u $USERNAME`
GROUPID=`id -g $USERNAME`

build() {
    docker build -f .rtr/Dockerfile -t $CONTAINER_NAME -q . > /dev/null
}

run() {
    echo "Running RTR on $SRC_DIR"
    jq -c '.steps[]' $RTR_CONFIG | while read step
    do
        STEP_DESC=`echo $step | jq -r '.description'`
        STEP_PARAMS=`echo $step | jq -r '.parameters | join(" ")'`
        echo "->Step: $STEP_DESC"
        docker run -v $SRC_DIR:/source -v $OUTPUT_DIR:/output -v $RTR_DIR:/rtr $CONTAINER_NAME /rtr/rtr.py -u $USERID -g $GROUPID -o /output -s /source $STEP_PARAMS
        docker_exit_code=$?
        if [ $docker_exit_code -ne 0 ]; then
            echo "Execution fail, RTR step: $STEP_DESC"
            exit $docker_exit_code
        fi
    done
    echo "RTR results on $OUTPUT_DIR directory."
}

build
run
