[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "engine-updown"
version = "0.0.1"
authors = [{ name = "Wazuh, Inc." }]
description = "Test utility to launch and stop Engine instances"
readme = "README.md"
requires-python = ">=3.8"
classifiers = ["Programming Language :: Python :: 3"]

dependencies = ["api-communication", "toml"]

[project.urls]
Homepage = "https://github.com/wazuh/wazuh/src/engine/tools/engine-updown"
