@startuml ER FIM DB

entity "file_entry" {
  path : text **<<PK>>**
  --
  mode : integer
  last_event : integer
  scanned : integer
  options : integer
  checksum : text
  dev : integer
  inode : integer
  size : integer
  perm : text
  attributes : text
  uid : integer
  gid : integer
  user_name : text
  group_name : text
  hash_md5 : text
  hash_sha1 : text
  hash_sha256 : text
  mtime : integer
}

entity "registry_key" {
  path : text **<<PK>>**
  arch : text **<<PK>>**
  --
  perm : text 
  uid : integer
  gid : integer
  user_name : text
  group_name : text
  mtime : integer
  scanned : integer
  last_event : integer
  checksum : text
  hash_full_path : text
}

entity "registry_data" {
  path : text **<<PK>>**
  arch : text **<<PK>>**
  name : text **<<PK>>**
  --
  registry_key_path **<<FK>>**
  registry_key_arch **<<FK>>**
  type : integer
  size : integer
  hash_md5 : text
  hash_sha1 : text
  hash_sha256 : text
  scanned : integer
  last_event : integer
  checksum : text
  hash_full_path : text
}
registry_data }o--|| registry_key


@enduml

