' Copyright (C) 2015, Wazuh Inc.
' Created by Wazuh, Inc. <info@wazuh.com>.
' This program is free software; you can redistribute it and/or modify it under the terms of GPLv2

@startuml sequence_diagram_fim_synchronization
actor "wazuh-agent" as agent
participant FIM_sync_thread
participant RSync_thread
actor "wazuh-manager" as manager

skinparam SequenceGroupBodyBackgroundColor #FFFFFF90

agent -> FIM_sync_thread : FIM sync thread started
FIM_sync_thread -> RSync_thread : Execute sync

loop #LightSkyBlue Each current interval seconds
    alt If at least "response timeout"\n seconds since last sync message
        alt If last sync was successful
            FIM_sync_thread -> FIM_sync_thread: Reset current interval
        end
        FIM_sync_thread -> RSync_thread : Execute sync
    else
        FIM_sync_thread -> FIM_sync_thread: Duplicate current interval
        alt If max interval reached
            FIM_sync_thread -> FIM_sync_thread: Limit interval to maximum configured
        end
    end
end loop

group #LightSkyBlue sync function
    RSync_thread -> manager : First sync msg\n("integrity_check_global"\nor "integrity_clear")
    alt
        manager -> RSync_thread : Manager response msg
        RSync_thread -> manager : Agent "state" msg
        note over RSync_thread, manager
        Synchronization is considered successful
        when these messages are not exchanged
        between manager and agent
        end note
    end
end

@enduml
