' Copyright (C) 2015, Wazuh Inc.
' Created by Wazuh, Inc. <info@wazuh.com>.
' This program is free software; you can redistribute it and/or modify it under the terms of GPLv2

@startuml sequence_diagram_db_fim
database "<agent-id>.db" as agent.db
actor "wazuh-manager" as manager
actor "wazuh-agent" as fim
participant os as os
participant rsync
participant dbsync
database fim.db as fdb

activate fim

fim -> dbsync ++: reset DB
dbsync -> fdb -- : reset


loop scan (each ""frequency"" seconds)
    group for each [directory]
        fim -> os ++: get data
        fim <-- os --: info
        fim -> dbsync++ : update DB with new file data
        dbsync -> fdb : save data DB
        dbsync <-- fdb
        fim <-- dbsync
        manager <- fim ++: send fim event
        manager --> fim
     end group
        dbsync--
end loop
        agent.db <- manager++: update db
        agent.db --> manager --

... sync databases ...

loop every ""sync frequency"" seconds



    fim -> rsync++ : get sync data
    rsync -> dbsync++ : get DB data
    dbsync -> fdb : get data
    dbsync <-- fdb
    rsync <-- dbsync-- : DB data
    rsync -> rsync : build sync data
    rsync --> fim --: sync data
    fim --> manager : send sync data
    manager -> agent.db: update DB
end loop
@enduml
