# Makefile for the decoders
# Daniel B. Cid <dcid@ossec.net>
# http://www.ossec.net

PT=../../../
NAME=ossec-analysisd

include ../../../Config.Make


plugins:
		$(CC) $(CFLAGS) -I../../ -c $(SOURCES)

clean:
		-${CLEAN}
