/* Copyright (C) 2015, Wazuh Inc.
 * Copyright (C) 2009 Trend Micro Inc.
 * All rights reserved.
 *
 * This program is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General Public
 * License (version 2) as published by the FSF - Free Software
 * Foundation
 *
 * In addition, as a special exception, the copyright holders give
 * permission to link the code of portions of this program with the
 * OpenSSL library under certain conditions as described in each
 * individual source file, and distribute linked combinations
 * including the two.
 *
 * You must obey the GNU General Public License in all respects
 * for all of the code used other than OpenSSL.  If you modify
 * file(s) with this exception, you may extend this exception to your
 * version of the file(s), but you are not obligated to do so.  If you
 * do not wish to do so, delete this exception statement from your
 * version.  If you delete this exception statement from all source
 * files in the program, then also delete it here.
 *
 */

#ifndef AUTHD_H
#define AUTHD_H

#ifndef ARGV0
#define ARGV0 "wazuh-authd"
#endif

#include "os_net.h"
#include "authd-config.h"
#include <pthread.h>
#include "ssl_op.h"
#include "sec.h"
#include "md5_op.h"
#include "sha1_op.h"

#define DEFAULT_PORT 1515
#define DEFAULT_CENTRALIZED_GROUP "default"
#define MAX_SSL_MSG_SIZE (OS_SIZE_65536 + OS_SIZE_4096)
#define SERVER_INDEX 0
#define STOP_FD (AUTH_POOL+1)

#define full(i, j) ((i + 1) % AUTH_POOL == j)
#define empty(i, j) (i == j)
#define forward(x) x = (x + 1) % AUTH_POOL

struct client {
    int socket;
    int index;
    union {
        struct in_addr *addr4;
        struct in6_addr *addr6;
    };
    bool is_ipv6;
    SSL *ssl;
    bool handshake_done;
    bool enrollment_ok;
    char ip[IPSIZE + 1];

    char* read_buffer;
    int  read_offset;

    char* write_buffer;
    int  write_offset;
    int  write_len;

    char* agentname;
    char* centralized_group;
    char* new_id;
};

struct keynode {
    char *id;
    char *name;
    char *ip;
    char *group;
    char *raw_key;
    /// Re-enrollment secret (#38993): 64 hex chars generated by local_add(), carried only until the writer
    /// persists it in global.db (never in client.keys); NULL for the legacy 1515 path and for removals.
    char *reenroll_secret;
    /// Set by add_rotate() (re-enrollment, #38993): the entry replaces an agent that already has a row in
    /// global.db, so the writer UPDATEs its credentials (set-agent-credentials) instead of inserting a
    /// row, and only touches its groups when the request named some.
    int rotate;
    /// Sequence of this transition in the identity journal (issue #39078, H03), 0 when it was not
    /// journaled (the legacy 1515 path, which generates no secret). It is what lets the writer
    /// forget the entry once the database write is COMMITTED, and not one moment earlier.
    long long journal_seq;
    struct keynode *next;
};

// Thread for internal server
void* run_local_server(void *arg);

// Append key to insertion queue. reenroll_secret may be NULL (legacy 1515 enrollment: no secret is
// generated for it, see local_add()).
void add_insert(const keyentry *entry, const char *group, const char *reenroll_secret, long long journal_seq);

// Append a rotated key to the insertion queue (re-enrollment, #38993): same fields as add_insert() plus
// the `rotate` flag. group may be NULL (the agent keeps its groups); reenroll_secret is the new one.
void add_rotate(const keyentry *entry, const char *group, const char *reenroll_secret, long long journal_seq);

// Append key to deletion queue
void add_remove(const keyentry *entry);

// Read configuration
int authd_read_config(const char *path);
cJSON *getAuthdConfig(void);
size_t authcom_dispatch(const char * command, char ** output);
size_t authcom_getconfig(const char * section, char ** output);

// Block signals
void authd_sigblock();

/**
 * @brief Validate if groups are valid for new enrollment
 * @param groups Comma separated string with new enrollment groups
 * @param response 2048 length buffer where the error response will be copied. NULL if no response is required
 * */
w_err_t w_auth_validate_groups(const char *groups, char *response);

/**
 * @brief Cleanup compiled regex for group validation (for testing)
 * */
void w_auth_validate_groups_cleanup(void);

/**
 * @brief Parse a raw buffer from agent request into enrollment data.
 * @param buf Raw buffer to be parsed
 * @param response 2048 length buffer where the error response will be copied
 * @param authpass Authentication password expected on the buffer, NULL if there isn't password
 * @param ip IP direction of the request. Can be override with IP parsed from buffer
 * @param agentname Pointer where parsed agent name will be allocated
 * @param groups Pointer where parsed groups will be allocated
 * @param key_hash Pointer where parsed key hash will be allocated
 * */
w_err_t w_auth_parse_data(const char* buf,
                          char *response,
                          const char *authpass,
                          char *ip,
                          char **agentname,
                          char **groups,
                          char **key_hash);

/**
 * @brief Validates if new enrollment is possible with provided data.
 * With force configuration disabled, if enrollment data is already registered, validation will fail.
 * With force configuration enabled, duplicated entry will be removed.
 * @param response 2048 length buffer where the error response will be copied
 * @param ip New enrollment ip direction
 * @param agentname New enrollment agent name
 * @param groups New enrollment groups
 * @param hash_key Hash of the key on the agent
 * */
w_err_t w_auth_validate_data(char *response,
                             const char *ip,
                             const char *agentname,
                             const char *groups,
                             const char *hash_key);

/**
 * @brief Validates if the old agent can be replaced and removes it.
 * @param key Key structure of the agent to be removed
 * @param hash_key Hash of the key on the agent
 * @param force_options Force configuration structure to define how the agent replacement must be handled.
 * @param str_result A message related to the result of the agent replacement. Must be freed by the caller.
 * @param warn Set to true when the rejection reflects a live identity conflict (the existing agent is still connected and does not self-heal); false for transient or expected rejections. May be NULL.
 * */
w_err_t w_auth_replace_agent(keyentry *key,
                             const char *key_hash,
                             authd_force_options_t *force_options,
                             char** str_result,
                             bool *warn);

/**
 * @brief Adds new agent with provided enrollment data.
 * @param response 2048 length buffer where the error response will be copied
 * @param ip New enrollment ip direction
 * @param agentname New enrollment agent name
 * @param id Pointer where new Agent ID will be allocated
 * @param key Pointer where new Agent key will be allocated
 * */
w_err_t w_auth_add_agent(char *response,
                         const char *ip,
                         const char *agentname,
                         char **id,
                         char **key);

/**
 * @brief Adds new agent from a local request
 * @param id Agent ID of the agent to be registered
 * @param ip Agent IP of the agent to be registered
 * @param groups Groups to which the agent belongs
 * @param key Agent key if was already registered
 * @param key_hash Hash of the agent key
 * @param force_options Options to decide if forcing the insertion
 * @return JSON object with the response
 * */
cJSON* local_add(const char *id,
                        const char *name,
                        const char *ip,
                        const char *groups,
                        const char *key,
                        const char *key_hash,
                        authd_force_options_t *force_options);

/**
 * @brief Forwards an "add" request to the master node over the cluster (worker nodes only).
 *        Any caller-supplied id/key/force are ignored -- the master always assigns the ID,
 *        generates the key, and decides force-replace using its own configuration, matching
 *        the network (port 1515) enrollment path's worker behavior.
 * @param name Name of the agent to be registered
 * @param ip IP of the agent to be registered
 * @param groups Groups to which the agent belongs
 * @param key_hash Hash of the agent key, used for the force/key-mismatch decision
 * @param token_id Enrollment token the agent presented (#38993), or NULL
 * @param reenroll_kid Re-enrollment (#38993): the agent id the bearer names, or NULL. The master
 *        verifies the bearer against that agent's secret and rotates its credentials in place.
 * @param reenroll_bearer The `wazuh-enroll+jwt` the agent re-enrolls with (with reenroll_kid), or NULL
 * @return JSON object with the response
 * */
cJSON* local_add_clustered(const char *name,
                           const char *ip,
                           const char *groups,
                           const char *key_hash,
                           const char *token_id,
                           const char *reenroll_kid,
                           const char *reenroll_bearer);

/**
 * @brief Returns a MD5 hash of some random data collected from different sources.
 *        The result must be freed by the caller.
 *
 * @return const char* The resulting hash or NULL on error.
 */
char *w_generate_random_pass();

/* Load the shared password (master): read it from @p path or generate+persist one.
 * Fail-closed on an invalid existing file; never returns NULL. Sets @p generated. */
char *w_authd_load_password(const char *path, bool *generated);

/* Read the shared password from @p path (cluster worker): never generates, persists,
 * nor exits. Returns NULL when missing/empty/short/unreadable. */
char *w_authd_read_password(const char *path);

extern char shost[512];
extern keystore keys;
extern volatile int write_pending;
/* --- The agent-deletion handoff journal --------------------------------------------------------
 *
 * PENDING_PURGES_FILE is no longer a queue with its own scheduler and retry ladder. It is a HANDOFF
 * JOURNAL holding only the ids currently between phase 1 and phase 4 of a deletion, and it is
 * normally empty: it drains at wazuh-db speed rather than at indexer speed. The purge itself is a
 * manager-task row, executed by the Task Manager's dispatcher, and authd's whole responsibility is
 * to make sure that row exists.
 *
 * The phases, in the order they run:
 *
 *   0. ADMIT OR REFUSE, on the REQUEST thread, before OS_DeleteKey -- purge_backlog_full(). It has
 *      to be here: by phase 1 the agent is already out of the in-memory keystore and the caller has
 *      already been told the deletion succeeded, so there is nothing left to refuse and nobody to
 *      tell. This is the one phase that can say no. BOTH paths that delete an agent take it -- the
 *      local socket's remove, and a force replacement, which is a deletion in every other respect
 *      and the higher-volume one.
 *   1. INTENT, before OS_WriteKeys -- purge_journal_append(). A local file write, no external
 *      dependency, so an outage anywhere else cannot block a client.keys write.
 *   2. OS_WriteKeys. The point of no return, and its RETURN VALUE IS CAPTURED.
 *   3. CREATE, only if step 2 succeeded. One row per id over the writer's own wazuh-db socket.
 *      Create commits inside its own command, so that `ok` is the durability acknowledgement.
 *   4. FORGET, on that ok -- purge_journal_drop().
 *
 * Gating 3 on 2 is load-bearing: the writer LOGS a failed OS_WriteKeys and falls through to the
 * removal loop, so without the gate authd would create purge rows for agents still on disk.
 *
 * A crash anywhere in that sequence is resolved at the next start by purge_journal_reconcile(),
 * which compares each line against the client.keys it has just read.
 */

/// One journaled deletion: the agent, when it was requested, and its sequence.
typedef struct purge_journal_entry_t {
    char id[16];
    time_t requested_at;
    /// Monotonic per-entry sequence, persisted. It is what makes the task id of a deletion
    /// derivable twice (phase 3 and reconciliation) without a second genuine deletion of the same
    /// agent colliding with the first -- which a wall-clock stamp could not promise.
    long long journal_seq;
} purge_journal_entry_t;

/// Recover the journal a previous run left behind, and raise the id counter past every id it
/// mentions. Call after OS_ReadKeys() and before ANY thread starts -- including the request
/// listeners, not just the writer: purge_is_pending() answers from the journal held in memory, so a
/// request served before this runs is judged against an empty one and can reassign an id whose
/// purge is still owed.
void purge_file_load(void);

/// Phase 0. Whether the deletion backlog is too deep to admit another one. Called on the request
/// thread; both of its terms are described at the definition.
bool purge_backlog_full(void);

/// Phase 1. Append @p count ids to the journal, assigning each the next sequence, and persist it.
/// Releases each id's removal-time reservation as the journal takes over as the durable record, so
/// an id is covered continuously from admission onwards.
///
/// @return A caller-owned array of @p count entries as journaled, or NULL when @p count is 0.
purge_journal_entry_t* purge_journal_append(char **ids, size_t count);

/// Phase 4. Drop these entries from the journal and persist the shorter file.
void purge_journal_drop(const purge_journal_entry_t *entries, size_t count);

/**
 * @brief Every deletion the journal still owes, as of now.
 *
 * Phase 3 works from this rather than from the ids the calling cycle happened to journal, so a
 * create that failed -- wazuh-db restarting, a socket timeout, or an admission bound that was full
 * at the time -- is retried by the next cycle instead of waiting for the next process start. That
 * is what makes "it stays journaled and will be retried" true: without it the untouched lines are
 * only ever revisited by purge_journal_reconcile(), and the agents behind them are already gone
 * from client.keys, so their documents stay orphaned for the lifetime of the process.
 *
 * Unlike purge_journal_reconcile() this decides nothing and changes nothing: no client.keys
 * comparison, no line dropped, no file written. Safe to call on every writer cycle.
 *
 * @param[out] count Number of entries returned.
 * @return A caller-owned array of @p count entries, or NULL when nothing is owed.
 */
purge_journal_entry_t* purge_journal_snapshot(size_t *count);

/// Startup reconciliation. For every journaled line, consult the client.keys already read: an
/// agent still listed there means the deletion never became final, so the line is dropped; an
/// absent one means phase 2 completed and the row is still owed.
///
/// @param[out] count Entries still owed.
/// @return A caller-owned array of them, or NULL when nothing is owed.
purge_journal_entry_t* purge_journal_reconcile(size_t *count);

/// Whether an id still owes a purge, so it must not be handed to a new agent. Answers from memory
/// when authd is still holding the deletion itself, and otherwise ASKS THE ROW, which is the only
/// authority once the deletion has been handed off. Fails closed.
///
/// BLOCKS for up to authd.wdb_timeout, so it must not be called with mutex_keys held.
bool purge_is_pending(const char *agent_id);

/**
 * @brief Reserve the right to rotate this agent's credentials.
 *
 * Taken BEFORE the request reads the agent's re-enrollment secret: the database keeps saying the
 * old secret until the writer updates it, so a second request that got that far would verify the
 * same bearer and hand out a second credential for one agent (issue #39078, H02).
 *
 * @param agent_id Agent to reserve.
 * @param generation Receives the rotations completed for this agent so far; re-check it under
 *                   mutex_keys before mutating, since a rotation may have completed while this
 *                   request was verifying.
 * @return true when the reservation was taken, false when another rotation already holds it.
 */
bool w_reenroll_reserve(const char *agent_id, unsigned int *generation);

/// Rotations completed for this agent so far.
unsigned int w_reenroll_generation(const char *agent_id);

/**
 * @brief Release a reservation whose transition was persisted, and count the rotation.
 *
 * Called by the writer on a successful credential update, and only then: a failed write leaves the
 * old secret in the database, so releasing there would let that secret authorise another rotation.
 */
void w_reenroll_complete(const char *agent_id);

/// Release a reservation whose request was rejected before anything was handed out. The agent's
/// slot is dropped when it has no completed rotation to remember, so the refusals cannot grow the
/// registry: the id comes from the request and is reserved before the agent is known to exist.
void w_reenroll_abandon(const char *agent_id);

/// How many agents the rotation registry is holding. For the tests: what they assert is that a
/// refused request leaves nothing behind.
unsigned int w_reenroll_slots(void);

/// The memory-only half of purge_is_pending(): whether the id is journaled or reserved here, which
/// is what authd knows without asking anyone. Never blocks, so it is the one that may be called
/// under mutex_keys -- as a re-check, after purge_is_pending() has already answered outside it.
bool purge_is_pending_locally(const char *agent_id);

/// Publish the manager-task backlog depth the writer measured, for phase 0's second term. Failing
/// to measure it must NOT be reported as zero: keep the last value instead, or a wazuh-db outage
/// would silently lift the bound.
void purge_pending_rows_update(int rows);

/* --- The identity transition journal -----------------------------------------------------------
 *
 * The other half of the same story (issue #39078, H03). An enrollment and a re-enrollment answer
 * with a key and a re-enrollment secret while the database write is still queued, so a wazuh-db
 * outage or a crash used to leave the agent holding credentials nothing else knows: it can talk to
 * remoted until client.keys is reloaded, and it can never re-enroll, because the row has no secret
 * or the previous one.
 *
 * PENDING_IDENTITIES_FILE holds those transitions, in the clear, from before the answer until the
 * database write is COMMITTED. In the clear because the verifier derives its signing key from the
 * real secret and client.keys does not carry it -- a hash would record that something happened and
 * restore nothing.
 *
 *   1. RECORD, on the request thread, before the keystore is mutated (re-enrollment) or right
 *      after the id is assigned (enrollment), and always before the answer is built. A failure
 *      here REFUSES the operation: 9031, and no credential is handed out.
 *   2. APPLY, on the writer, as the insert or the credential update it always did.
 *   3. COMMIT, once per cycle: `global commit`. An `ok` from insert-agent is not durability --
 *      wazuh-db runs a deferred transaction and commits it on its own clock (wdb_commit_old).
 *   4. FORGET, on that commit -- and only then is a rotation's reservation released.
 *
 * The writer wakes on its own clock while anything is owed, so a manager that goes idle during an
 * outage still finishes the job; a crash is resolved at the next start by
 * identity_journal_reconcile(), which judges each line against the client.keys just read.
 */

/// How many transitions may be in flight at once. Past it a new one is REFUSED (9031) rather than
/// performed unrecorded, and never at the expense of an older entry: every line here is a
/// credential an agent already holds.
#define IDENTITY_JOURNAL_MAX_ENTRIES 5000

/// Largest file that is loaded back. The bound above keeps a legitimate file two orders of
/// magnitude below this, so anything bigger is corruption, not a busy manager.
#define IDENTITY_JOURNAL_MAX_BYTES (8 * 1024 * 1024)

/// One recorded transition: the agent as it was named, and the credential it was given.
typedef struct identity_journal_entry_t {
    long long seq;      ///< Address of the entry, for dropping it once committed. Never reused.
    char *id;
    char *name;
    char *ip;
    char *key;          ///< The agent key, as handed to the agent.
    char *secret;       ///< The re-enrollment secret, likewise. Wiped, not just freed.
    bool rotate;        ///< A re-enrollment (UPDATE of an existing row) rather than an enrollment.
    time_t requested_at;
} identity_journal_entry_t;

/// Point the journal at @p path (NULL restores the default) AND forget whatever is held in
/// memory. For the tests, which run in a temporary tree; production never calls it.
void identity_journal_init(const char *path);

/// Step 1. Record a transition and persist it, appending one line.
///
/// @return true when the line is on disk. **false means the caller must not perform the
/// operation**: nothing else stores the secret, so an unrecorded transition is an agent that can
/// never re-enroll.
bool identity_journal_append(const char *id,
                             const char *name,
                             const char *ip,
                             const char *key,
                             const char *secret,
                             bool rotate,
                             long long *seq);

/// Whether the journal cannot admit another transition right now.
///
/// Phase 0, and it exists because of WHERE a refusal can still be free: an enrollment that
/// resolves a duplicate name or IP with <force> deletes the previous agent while it validates, so
/// a caller told "no room" after that point would lose that agent for nothing. Asked before
/// anything is mutated, exactly like purge_backlog_full() on the deletion path.
bool identity_journal_full(void);

/// How many transitions are still owed to the database. The writer's timed wake depends on it.
size_t identity_journal_pending(void);

/// Highest sequence the journal has handed out, including the entries loaded from disk. The writer
/// starts its own mark here, so what a previous run left behind is recoverable at once.
long long identity_journal_last_seq(void);

/// Up to @p max transitions still owed (0 = all), as of now. Decides nothing and changes nothing.
///
/// @param max Largest batch to return, 0 for no limit.
/// @param upto_seq Highest sequence the caller is willing to see, 0 for no limit. The writer passes
///                 the last one it has already taken work for: a transition appended after that has
///                 its key still on its way to client.keys, and applying it here would let the
///                 journal forget a credential nothing else records yet.
/// @param[out] count Number of entries returned.
/// @return A caller-owned array, released with identity_journal_free().
identity_journal_entry_t* identity_journal_snapshot(size_t max, long long upto_seq, size_t *count);

/// Release a snapshot, wiping the credentials it carries.
void identity_journal_free(identity_journal_entry_t *entries, size_t count);

/// Step 4. Drop these sequences and rewrite the shorter file.
///
/// @return How many of them were still journaled.
size_t identity_journal_drop(const long long *seqs, size_t count);

/// Read the journal a previous run left behind. Call after OS_ReadKeys() and before any thread
/// starts, like purge_file_load().
void identity_journal_load(void);

/// Startup reconciliation, against the client.keys already read. The generation is decided by the
/// JOURNAL's own order, not by the key in client.keys, which the writer may never have got to:
/// an id absent from client.keys owes nothing, an entry with a later one for the same agent is the
/// previous generation, and anything else is still owed -- even when client.keys names another
/// key, which is precisely the crash this journal exists for. Retained rotations get their
/// reservation back before any thread starts.
///
/// @return How many transitions survived.
size_t identity_journal_reconcile(void);

/// Record the highest id handed out so far, so it is never reused after a restart.
void purge_last_id_update(int id_counter);

/// Free the in-memory journal at shutdown and report what is still owed. The file is kept.
void purge_journal_discard(void);

extern volatile int running;
extern pthread_mutex_t mutex_keys;
extern pthread_cond_t cond_pending;
extern authd_config_t config;

#endif /* AUTHD_H */
