#!/usr/bin/env python3
# Copyright (C) 2015, Wazuh Inc.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

"""Tests for wazuh-migrate-identity.py.

Builds a 4.x and a 5.0 installation tree in a temporary directory and runs the tool against them.
The target schema is the repository's own src/wazuh_db/schemas/schema_global.sql, so a schema change
that the transform cannot follow fails here rather than on an operator's manager.

    python3 tools/migration/test_wazuh_migrate_identity.py
"""

import importlib.util
import json
import os
import shutil
import sqlite3
import tarfile
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
TARGET_SCHEMA = os.path.join(REPO, "src", "wazuh_db", "schemas", "schema_global.sql")

_spec = importlib.util.spec_from_file_location(
    "wazuh_migrate_identity", os.path.join(HERE, "wazuh-migrate-identity.py"))
tool = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(tool)


# The 4.x agent table, as 4.14 defines it. Enough of the real shape to exercise the transform:
# the columns 5.0 dropped, the ones it kept, and the os_platform it derives os_type from.
SOURCE_SCHEMA = """
CREATE TABLE agent (
    id INTEGER PRIMARY KEY,
    name TEXT,
    ip TEXT,
    register_ip TEXT,
    internal_key TEXT,
    os_name TEXT,
    os_version TEXT,
    os_major TEXT,
    os_minor TEXT,
    os_codename TEXT,
    os_build TEXT,
    os_platform TEXT,
    os_uname TEXT,
    os_arch TEXT,
    version TEXT,
    config_sum TEXT,
    merged_sum TEXT,
    manager_host TEXT,
    node_name TEXT DEFAULT 'unknown',
    date_add INTEGER NOT NULL,
    last_keepalive INTEGER,
    'group' TEXT,
    group_hash TEXT,
    group_sync_status TEXT NOT NULL DEFAULT 'synced',
    sync_status TEXT NOT NULL DEFAULT 'synced',
    connection_status TEXT NOT NULL DEFAULT 'never_connected',
    disconnection_time INTEGER DEFAULT 0,
    group_config_status TEXT NOT NULL DEFAULT 'not synced',
    status_code INTEGER DEFAULT 0
);
CREATE TABLE 'group' (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);
CREATE TABLE belongs (
    id_agent INTEGER,
    id_group INTEGER,
    priority INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (id_agent, id_group)
);
CREATE TABLE labels (
    id_agent INTEGER,
    key TEXT,
    value TEXT,
    id_checksum TEXT,
    PRIMARY KEY (id_agent, key)
);
CREATE TABLE metadata (
    key TEXT PRIMARY KEY,
    value TEXT
);
INSERT INTO metadata (key, value) VALUES ('db_version', '7');
"""

AGENTS = [
    # id, name, os_platform, expected os_type, groups
    (1, "web-ubuntu24", "ubuntu", "linux", ["linux-servers", "pci-scope"]),
    (2, "win11-lab", "windows", "windows", ["default", "pci-scope"]),
    (3, "db-al2023", "amzn", "linux", ["db-servers", "pci-scope"]),
    (4, "mac-build", "darwin", "macos", ["default"]),
]

GROUPS = ["default", "linux-servers", "db-servers", "pci-scope"]


def build_source(root):
    """A 4.x installation holding four agents in four groups."""
    for relative in ("etc/shared/default", "etc/shared/linux-servers", "etc/shared/db-servers",
                     "etc/shared/pci-scope", "queue/db", "api/configuration/security", "var/run"):
        os.makedirs(os.path.join(root, relative), exist_ok=True)

    with open(os.path.join(root, "VERSION.json"), "w") as handle:
        json.dump({"version": "4.14.7"}, handle)

    with open(os.path.join(root, "etc", "client.keys"), "w") as handle:
        for agent_id, name, _, _, _ in AGENTS:
            handle.write("%03d %s any %064x\n" % (agent_id, name, agent_id))

    with open(os.path.join(root, "etc", "authd.pass"), "w") as handle:
        handle.write("MigrationLab2026\n")

    for group in GROUPS:
        with open(os.path.join(root, "etc", "shared", group, "agent.conf"), "w") as handle:
            handle.write("<agent_config><!-- %s --></agent_config>\n" % group)
    # Regenerated by the manager; must never reach the target.
    with open(os.path.join(root, "etc", "shared", "linux-servers", "merged.mg"), "w") as handle:
        handle.write("stale\n")

    database = os.path.join(root, "queue", "db", "global.db")
    connection = sqlite3.connect(database)
    connection.executescript(SOURCE_SCHEMA)
    connection.execute(
        "INSERT INTO agent (id, name, ip, register_ip, date_add, os_platform, os_uname,"
        " connection_status) VALUES (0, 'mgr4', '127.0.0.1', '127.0.0.1', 1, NULL, NULL,"
        " 'never_connected')")
    for agent_id, name, platform, _, groups in AGENTS:
        connection.execute(
            "INSERT INTO agent (id, name, ip, register_ip, internal_key, os_platform, os_uname,"
            " os_codename, config_sum, manager_host, version, date_add, `group`,"
            " connection_status) VALUES (?, ?, ?, 'any', ?, ?, 'uname', 'codename', 'sum',"
            " 'mgr4', 'Wazuh v4.14.7', ?, ?, 'active')",
            (agent_id, name, "10.0.0.%d" % agent_id, "%064x" % agent_id, platform,
             1700000000 + agent_id, ",".join(groups)))
    for group in GROUPS:
        connection.execute("INSERT INTO `group` (name) VALUES (?)", (group,))
    group_ids = {row[1]: row[0] for row in connection.execute("SELECT id, name FROM `group`")}
    for agent_id, _, _, _, groups in AGENTS:
        for priority, group in enumerate(groups):
            connection.execute(
                "INSERT INTO belongs (id_agent, id_group, priority) VALUES (?, ?, ?)",
                (agent_id, group_ids[group], priority))
    connection.execute("INSERT INTO labels (id_agent, key, value) VALUES (1, 'env', 'prod')")
    connection.commit()
    connection.close()

    rbac = os.path.join(root, "api", "configuration", "security", "rbac.db")
    connection = sqlite3.connect(rbac)
    connection.executescript(
        "CREATE TABLE users (id INTEGER PRIMARY KEY, username TEXT, password TEXT);"
        "INSERT INTO users VALUES (1, 'wazuh', 'hash1'), (100, 'soc-analyst', 'hash2');"
        "CREATE TABLE policies (id INTEGER PRIMARY KEY, name TEXT);"
        "INSERT INTO policies VALUES (1, 'agents_all_resourceless');"
        "PRAGMA user_version = 1;")
    connection.commit()
    connection.close()
    return root


def build_target(root):
    """A 5.0 installation as the package leaves it: empty registry, its own default group."""
    for relative in ("etc/shared/default", "queue/db", "api/configuration/security", "var/run"):
        os.makedirs(os.path.join(root, relative), exist_ok=True)

    with open(os.path.join(root, "VERSION.json"), "w") as handle:
        json.dump({"version": "5.0.0"}, handle)
    with open(os.path.join(root, "etc", "client.keys"), "w"):
        pass
    with open(os.path.join(root, "etc", "shared", "default", "agent.conf"), "w") as handle:
        handle.write("<agent_config><!-- 5.0 default --></agent_config>\n")

    database = os.path.join(root, "queue", "db", "global.db")
    with open(TARGET_SCHEMA) as handle:
        schema = handle.read()
    connection = sqlite3.connect(database)
    connection.executescript(schema)
    connection.execute(
        "INSERT INTO `group` (name) VALUES ('default')")
    connection.execute(
        "INSERT INTO agent (id, name, ip, register_ip, date_add) VALUES"
        " (0, 'mgr5', '127.0.0.1', '127.0.0.1', 1)")
    connection.commit()
    connection.close()
    return root


class MigrationToolTest(unittest.TestCase):

    def setUp(self):
        if not os.path.isfile(TARGET_SCHEMA):
            self.skipTest("%s not found; run from a repository checkout." % TARGET_SCHEMA)
        self.workspace = tempfile.TemporaryDirectory()
        base = self.workspace.name
        self.source = build_source(os.path.join(base, "source"))
        self.target = build_target(os.path.join(base, "target"))
        self.bundle = os.path.join(base, "bundle")

    def tearDown(self):
        self.workspace.cleanup()

    # -- helpers

    def export(self, *extra):
        return tool.main(["export", self.bundle, "--source-dir", self.source] + list(extra))

    def do_import(self, *extra):
        return tool.main(["import", self.bundle, "--target-dir", self.target] + list(extra))

    def check(self, *extra):
        return tool.main(["check", self.bundle, "--target-dir", self.target] + list(extra))

    def target_registry(self):
        return tool.open_ro(os.path.join(self.target, "queue", "db", "global.db"))

    # -- the round trip

    def test_round_trip_preserves_identity(self):
        self.assertEqual(0, self.export("--with-password"))
        self.assertEqual(0, self.do_import("--with-password", "--with-rbac"))
        self.assertEqual(0, self.check())

        with self.target_registry() as connection:
            rows = {row[0]: row for row in connection.execute(
                "SELECT id, name, os_type, `group`, connection_status, date_add, version"
                " FROM agent WHERE id > 0")}
            self.assertEqual(len(AGENTS), len(rows))
            for agent_id, name, _, os_type, groups in AGENTS:
                row = rows[agent_id]
                self.assertEqual(name, row[1], "agent %d kept its name" % agent_id)
                self.assertEqual(os_type, row[2], "agent %d os_type" % agent_id)
                self.assertEqual(",".join(groups), row[3])
                self.assertEqual("disconnected", row[4],
                                 "an imported agent is disconnected until it reconnects")
                self.assertEqual(1700000000 + agent_id, row[5], "registration date carried")
                self.assertEqual("Wazuh v4.14.7", row[6])

            # Row 0 is the manager's own and belongs to the target, not the bundle.
            self.assertEqual("mgr5", connection.execute(
                "SELECT name FROM agent WHERE id = 0").fetchone()[0])

            membership = {}
            for agent_id, group in connection.execute(
                    "SELECT b.id_agent, g.name FROM belongs b"
                    " JOIN `group` g ON g.id = b.id_group ORDER BY b.priority"):
                membership.setdefault(agent_id, []).append(group)
            for agent_id, _, _, _, groups in AGENTS:
                self.assertEqual(sorted(groups), sorted(membership[agent_id]),
                                 "agent %d group membership" % agent_id)

    def test_keys_and_groups_land_with_the_right_content(self):
        self.assertEqual(0, self.export())
        self.assertEqual(0, self.do_import())

        with open(os.path.join(self.target, "etc", "client.keys")) as handle:
            keys = handle.read()
        for agent_id, name, _, _, _ in AGENTS:
            self.assertIn("%03d %s" % (agent_id, name), keys)

        shared = os.path.join(self.target, "etc", "shared")
        for group in GROUPS:
            if group == "default":
                continue
            self.assertTrue(os.path.isdir(os.path.join(shared, group)), group)
        self.assertFalse(
            os.path.exists(os.path.join(shared, "linux-servers", "merged.mg")),
            "merged.mg is regenerated by the manager and must not be carried")
        with open(os.path.join(shared, "default", "agent.conf")) as handle:
            self.assertIn("5.0 default", handle.read(),
                          "the target's own default group must survive the import")

    def test_password_and_rbac_are_opt_in(self):
        self.assertEqual(0, self.export("--with-password"))
        self.assertEqual(0, self.do_import())
        self.assertFalse(os.path.exists(os.path.join(self.target, "etc", "authd.pass")))
        rbac = os.path.join(self.target, "api", "configuration", "security", "rbac.db")
        self.assertFalse(os.path.exists(rbac))

    def test_rbac_import_stages_the_api_upgrade(self):
        self.assertEqual(0, self.export())
        self.assertEqual(0, self.do_import("--with-rbac"))
        rbac = os.path.join(self.target, "api", "configuration", "security", "rbac.db")
        with tool.open_ro(rbac) as connection:
            self.assertEqual(0, connection.execute("PRAGMA user_version").fetchone()[0],
                             "version 0 is what makes the API rebuild its 5.0 defaults")
            self.assertEqual(
                {"wazuh", "soc-analyst"},
                {row[0] for row in connection.execute("SELECT username FROM users")})

    def test_dry_run_changes_nothing(self):
        self.assertEqual(0, self.export())
        before = os.path.getmtime(os.path.join(self.target, "queue", "db", "global.db"))
        self.assertEqual(0, self.do_import("--dry-run"))
        with self.target_registry() as connection:
            self.assertEqual(0, connection.execute(
                "SELECT count(*) FROM agent WHERE id > 0").fetchone()[0])
        self.assertEqual(before,
                         os.path.getmtime(os.path.join(self.target, "queue", "db", "global.db")))
        self.assertFalse(os.path.exists(os.path.join(self.target, "etc", "client.keys")) and
                         os.path.getsize(os.path.join(self.target, "etc", "client.keys")) > 0)

    # -- refusals

    def test_export_refuses_a_5x_source(self):
        self.assertEqual(2, tool.main(["export", self.bundle, "--source-dir", self.target]))
        self.assertFalse(os.path.exists(self.bundle))

    def test_export_refuses_an_unknown_source_schema(self):
        database = os.path.join(self.source, "queue", "db", "global.db")
        connection = sqlite3.connect(database)
        connection.execute("UPDATE metadata SET value = '99' WHERE key = 'db_version'")
        connection.commit()
        connection.close()
        self.assertEqual(2, self.export())
        self.assertFalse(os.path.exists(self.bundle), "no partial bundle is left behind")

    def test_export_refuses_a_running_manager(self):
        with open(os.path.join(self.source, "var", "run", "wazuh-remoted.pid"), "w"):
            pass
        self.assertEqual(2, self.export())

    def test_import_refuses_a_running_manager(self):
        self.assertEqual(0, self.export())
        with open(os.path.join(self.target, "var", "run",
                               "wazuh-manager-remoted.pid"), "w"):
            pass
        self.assertEqual(2, self.do_import())

    def test_import_refuses_a_worker(self):
        self.assertEqual(0, self.export())
        with open(os.path.join(self.target, "etc", "wazuh-manager.conf"), "w") as handle:
            handle.write("<wazuh_config><cluster><node_type>worker</node_type>"
                         "</cluster></wazuh_config>")
        self.assertEqual(2, self.do_import())

    def test_import_refuses_a_populated_registry_without_writing(self):
        self.assertEqual(0, self.export())
        self.assertEqual(0, self.do_import())
        keys = os.path.join(self.target, "etc", "client.keys")
        with open(keys, "a") as handle:
            handle.write("005 later-agent any %064x\n" % 5)
        with open(keys) as handle:
            before = handle.read()
        self.assertEqual(2, self.do_import())
        with open(keys) as handle:
            self.assertEqual(before, handle.read(),
                             "a refused import must not have installed anything first")

    def test_import_refuses_a_tampered_bundle(self):
        self.assertEqual(0, self.export())
        with open(os.path.join(self.bundle, "client.keys"), "a") as handle:
            handle.write("006 rogue any %064x\n" % 6)
        self.assertEqual(2, self.do_import())

    def test_import_refuses_a_bundle_escaping_the_group_tree(self):
        self.assertEqual(0, self.export())
        archive = os.path.join(self.bundle, "groups.tar.gz")
        escape = os.path.join(self.workspace.name, "escape.conf")
        with open(escape, "w") as handle:
            handle.write("nope\n")
        with tarfile.open(archive, "w:gz") as tar:
            tar.add(escape, arcname="../../etc/escaped.conf")
        manifest_path = os.path.join(self.bundle, "manifest.json")
        with open(manifest_path) as handle:
            manifest = json.load(handle)
        manifest["files"]["groups.tar.gz"] = tool.sha256_of(archive)
        with open(manifest_path, "w") as handle:
            json.dump(manifest, handle)
        self.assertEqual(2, self.do_import())
        self.assertFalse(os.path.exists(os.path.join(self.target, "etc", "escaped.conf")))

    # -- check

    def test_check_reports_a_missing_agent(self):
        self.assertEqual(0, self.export())
        self.assertEqual(0, self.do_import())
        connection = sqlite3.connect(os.path.join(self.target, "queue", "db", "global.db"))
        connection.execute("DELETE FROM agent WHERE id = 2")
        connection.commit()
        connection.close()
        self.assertEqual(1, self.check())

    def test_check_reports_a_missing_group_folder(self):
        self.assertEqual(0, self.export())
        self.assertEqual(0, self.do_import())
        shutil.rmtree(os.path.join(self.target, "etc", "shared", "pci-scope"))
        self.assertEqual(1, self.check())


if __name__ == "__main__":
    unittest.main(verbosity=2)
