#!/bin/bash

rpm -e ossec-hids-server-FC7
rpm -e ossec-hids-local-FC7
rpm -e ossec-hids-agent-FC7

rm -fr /var/ossec/ 

for A in ossec ossecm ossecr ; do /usr/sbin/userdel -r $A ; done 

/usr/sbin/groupdel ossec

/sbin/chkconfig ossec off
/sbin/chkconfig --del ossec

# Remove init.d file
[ -f /etc/init.d/ossec ] && rm /etc/init.d/ossec


