// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: archiver.proto

#include "archiver.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace com {
namespace wazuh {
namespace api {
namespace engine {
namespace archiver {
PROTOBUF_CONSTEXPR ArchiverActivate_Request::ArchiverActivate_Request(
    ::_pbi::ConstantInitialized) {}
struct ArchiverActivate_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArchiverActivate_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArchiverActivate_RequestDefaultTypeInternal() {}
  union {
    ArchiverActivate_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArchiverActivate_RequestDefaultTypeInternal _ArchiverActivate_Request_default_instance_;
PROTOBUF_CONSTEXPR ArchiverDeactivate_Request::ArchiverDeactivate_Request(
    ::_pbi::ConstantInitialized) {}
struct ArchiverDeactivate_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArchiverDeactivate_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArchiverDeactivate_RequestDefaultTypeInternal() {}
  union {
    ArchiverDeactivate_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArchiverDeactivate_RequestDefaultTypeInternal _ArchiverDeactivate_Request_default_instance_;
PROTOBUF_CONSTEXPR ArchiverStatus_Request::ArchiverStatus_Request(
    ::_pbi::ConstantInitialized) {}
struct ArchiverStatus_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArchiverStatus_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArchiverStatus_RequestDefaultTypeInternal() {}
  union {
    ArchiverStatus_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArchiverStatus_RequestDefaultTypeInternal _ArchiverStatus_Request_default_instance_;
PROTOBUF_CONSTEXPR ArchiverStatus_Response::ArchiverStatus_Response(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_.active_)*/false} {}
struct ArchiverStatus_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArchiverStatus_ResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArchiverStatus_ResponseDefaultTypeInternal() {}
  union {
    ArchiverStatus_Response _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArchiverStatus_ResponseDefaultTypeInternal _ArchiverStatus_Response_default_instance_;
}  // namespace archiver
}  // namespace engine
}  // namespace api
}  // namespace wazuh
}  // namespace com
static ::_pb::Metadata file_level_metadata_archiver_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_archiver_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_archiver_2eproto = nullptr;

const uint32_t TableStruct_archiver_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::archiver::ArchiverActivate_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::archiver::ArchiverDeactivate_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::archiver::ArchiverStatus_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::archiver::ArchiverStatus_Response, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::archiver::ArchiverStatus_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::archiver::ArchiverStatus_Response, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::archiver::ArchiverStatus_Response, _impl_.error_),
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::archiver::ArchiverStatus_Response, _impl_.active_),
  ~0u,
  0,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::com::wazuh::api::engine::archiver::ArchiverActivate_Request)},
  { 6, -1, -1, sizeof(::com::wazuh::api::engine::archiver::ArchiverDeactivate_Request)},
  { 12, -1, -1, sizeof(::com::wazuh::api::engine::archiver::ArchiverStatus_Request)},
  { 18, 27, -1, sizeof(::com::wazuh::api::engine::archiver::ArchiverStatus_Response)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::com::wazuh::api::engine::archiver::_ArchiverActivate_Request_default_instance_._instance,
  &::com::wazuh::api::engine::archiver::_ArchiverDeactivate_Request_default_instance_._instance,
  &::com::wazuh::api::engine::archiver::_ArchiverStatus_Request_default_instance_._instance,
  &::com::wazuh::api::engine::archiver::_ArchiverStatus_Response_default_instance_._instance,
};

const char descriptor_table_protodef_archiver_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016archiver.proto\022\035com.wazuh.api.engine.a"
  "rchiver\032\014engine.proto\"\032\n\030ArchiverActivat"
  "e_Request\"\034\n\032ArchiverDeactivate_Request\""
  "\030\n\026ArchiverStatus_Request\"{\n\027ArchiverSta"
  "tus_Response\0222\n\006status\030\001 \001(\0162\".com.wazuh"
  ".api.engine.ReturnStatus\022\022\n\005error\030\002 \001(\tH"
  "\000\210\001\001\022\016\n\006active\030\003 \001(\010B\010\n\006_errorb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_archiver_2eproto_deps[1] = {
  &::descriptor_table_engine_2eproto,
};
static ::_pbi::once_flag descriptor_table_archiver_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_archiver_2eproto = {
    false, false, 278, descriptor_table_protodef_archiver_2eproto,
    "archiver.proto",
    &descriptor_table_archiver_2eproto_once, descriptor_table_archiver_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_archiver_2eproto::offsets,
    file_level_metadata_archiver_2eproto, file_level_enum_descriptors_archiver_2eproto,
    file_level_service_descriptors_archiver_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_archiver_2eproto_getter() {
  return &descriptor_table_archiver_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_archiver_2eproto(&descriptor_table_archiver_2eproto);
namespace com {
namespace wazuh {
namespace api {
namespace engine {
namespace archiver {

// ===================================================================

class ArchiverActivate_Request::_Internal {
 public:
};

ArchiverActivate_Request::ArchiverActivate_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:com.wazuh.api.engine.archiver.ArchiverActivate_Request)
}
ArchiverActivate_Request::ArchiverActivate_Request(const ArchiverActivate_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ArchiverActivate_Request* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.wazuh.api.engine.archiver.ArchiverActivate_Request)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ArchiverActivate_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ArchiverActivate_Request::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ArchiverActivate_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_archiver_2eproto_getter, &descriptor_table_archiver_2eproto_once,
      file_level_metadata_archiver_2eproto[0]);
}

// ===================================================================

class ArchiverDeactivate_Request::_Internal {
 public:
};

ArchiverDeactivate_Request::ArchiverDeactivate_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:com.wazuh.api.engine.archiver.ArchiverDeactivate_Request)
}
ArchiverDeactivate_Request::ArchiverDeactivate_Request(const ArchiverDeactivate_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ArchiverDeactivate_Request* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.wazuh.api.engine.archiver.ArchiverDeactivate_Request)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ArchiverDeactivate_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ArchiverDeactivate_Request::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ArchiverDeactivate_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_archiver_2eproto_getter, &descriptor_table_archiver_2eproto_once,
      file_level_metadata_archiver_2eproto[1]);
}

// ===================================================================

class ArchiverStatus_Request::_Internal {
 public:
};

ArchiverStatus_Request::ArchiverStatus_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:com.wazuh.api.engine.archiver.ArchiverStatus_Request)
}
ArchiverStatus_Request::ArchiverStatus_Request(const ArchiverStatus_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ArchiverStatus_Request* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.wazuh.api.engine.archiver.ArchiverStatus_Request)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ArchiverStatus_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ArchiverStatus_Request::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ArchiverStatus_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_archiver_2eproto_getter, &descriptor_table_archiver_2eproto_once,
      file_level_metadata_archiver_2eproto[2]);
}

// ===================================================================

class ArchiverStatus_Response::_Internal {
 public:
  using HasBits = decltype(std::declval<ArchiverStatus_Response>()._impl_._has_bits_);
  static void set_has_error(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

ArchiverStatus_Response::ArchiverStatus_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
}
ArchiverStatus_Response::ArchiverStatus_Response(const ArchiverStatus_Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ArchiverStatus_Response* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.error_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.active_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_error()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.status_, &from._impl_.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.active_) -
    reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.active_));
  // @@protoc_insertion_point(copy_constructor:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
}

inline void ArchiverStatus_Response::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.error_){}
    , decltype(_impl_.status_){0}
    , decltype(_impl_.active_){false}
  };
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ArchiverStatus_Response::~ArchiverStatus_Response() {
  // @@protoc_insertion_point(destructor:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ArchiverStatus_Response::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_.Destroy();
}

void ArchiverStatus_Response::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ArchiverStatus_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.error_.ClearNonDefaultToEmpty();
  }
  ::memset(&_impl_.status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.active_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.active_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ArchiverStatus_Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .com.wazuh.api.engine.ReturnStatus status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::com::wazuh::api::engine::ReturnStatus>(val));
        } else
          goto handle_unusual;
        continue;
      // optional string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "com.wazuh.api.engine.archiver.ArchiverStatus_Response.error"));
        } else
          goto handle_unusual;
        continue;
      // bool active = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.active_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ArchiverStatus_Response::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.wazuh.api.engine.ReturnStatus status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // optional string error = 2;
  if (_internal_has_error()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.wazuh.api.engine.archiver.ArchiverStatus_Response.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  // bool active = 3;
  if (this->_internal_active() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_active(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
  return target;
}

size_t ArchiverStatus_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string error = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  // .com.wazuh.api.engine.ReturnStatus status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  // bool active = 3;
  if (this->_internal_active() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ArchiverStatus_Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ArchiverStatus_Response::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ArchiverStatus_Response::GetClassData() const { return &_class_data_; }


void ArchiverStatus_Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ArchiverStatus_Response*>(&to_msg);
  auto& from = static_cast<const ArchiverStatus_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_error()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_active() != 0) {
    _this->_internal_set_active(from._internal_active());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ArchiverStatus_Response::CopyFrom(const ArchiverStatus_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.wazuh.api.engine.archiver.ArchiverStatus_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArchiverStatus_Response::IsInitialized() const {
  return true;
}

void ArchiverStatus_Response::InternalSwap(ArchiverStatus_Response* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ArchiverStatus_Response, _impl_.active_)
      + sizeof(ArchiverStatus_Response::_impl_.active_)
      - PROTOBUF_FIELD_OFFSET(ArchiverStatus_Response, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ArchiverStatus_Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_archiver_2eproto_getter, &descriptor_table_archiver_2eproto_once,
      file_level_metadata_archiver_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace archiver
}  // namespace engine
}  // namespace api
}  // namespace wazuh
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::wazuh::api::engine::archiver::ArchiverActivate_Request*
Arena::CreateMaybeMessage< ::com::wazuh::api::engine::archiver::ArchiverActivate_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::wazuh::api::engine::archiver::ArchiverActivate_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::com::wazuh::api::engine::archiver::ArchiverDeactivate_Request*
Arena::CreateMaybeMessage< ::com::wazuh::api::engine::archiver::ArchiverDeactivate_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::wazuh::api::engine::archiver::ArchiverDeactivate_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::com::wazuh::api::engine::archiver::ArchiverStatus_Request*
Arena::CreateMaybeMessage< ::com::wazuh::api::engine::archiver::ArchiverStatus_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::wazuh::api::engine::archiver::ArchiverStatus_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::com::wazuh::api::engine::archiver::ArchiverStatus_Response*
Arena::CreateMaybeMessage< ::com::wazuh::api::engine::archiver::ArchiverStatus_Response >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::wazuh::api::engine::archiver::ArchiverStatus_Response >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
