// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_dumper.proto

#include "event_dumper.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace com {
namespace wazuh {
namespace api {
namespace engine {
namespace event_dumper {
PROTOBUF_CONSTEXPR EventDumperActivate_Request::EventDumperActivate_Request(
    ::_pbi::ConstantInitialized) {}
struct EventDumperActivate_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDumperActivate_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDumperActivate_RequestDefaultTypeInternal() {}
  union {
    EventDumperActivate_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDumperActivate_RequestDefaultTypeInternal _EventDumperActivate_Request_default_instance_;
PROTOBUF_CONSTEXPR EventDumperDeactivate_Request::EventDumperDeactivate_Request(
    ::_pbi::ConstantInitialized) {}
struct EventDumperDeactivate_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDumperDeactivate_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDumperDeactivate_RequestDefaultTypeInternal() {}
  union {
    EventDumperDeactivate_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDumperDeactivate_RequestDefaultTypeInternal _EventDumperDeactivate_Request_default_instance_;
PROTOBUF_CONSTEXPR EventDumperStatus_Request::EventDumperStatus_Request(
    ::_pbi::ConstantInitialized) {}
struct EventDumperStatus_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDumperStatus_RequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDumperStatus_RequestDefaultTypeInternal() {}
  union {
    EventDumperStatus_Request _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDumperStatus_RequestDefaultTypeInternal _EventDumperStatus_Request_default_instance_;
PROTOBUF_CONSTEXPR EventDumperStatus_Response::EventDumperStatus_Response(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.error_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_.active_)*/false} {}
struct EventDumperStatus_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDumperStatus_ResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDumperStatus_ResponseDefaultTypeInternal() {}
  union {
    EventDumperStatus_Response _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDumperStatus_ResponseDefaultTypeInternal _EventDumperStatus_Response_default_instance_;
}  // namespace event_dumper
}  // namespace engine
}  // namespace api
}  // namespace wazuh
}  // namespace com
static ::_pb::Metadata file_level_metadata_event_5fdumper_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_event_5fdumper_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_event_5fdumper_2eproto = nullptr;

const uint32_t TableStruct_event_5fdumper_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::event_dumper::EventDumperActivate_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::event_dumper::EventDumperDeactivate_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::event_dumper::EventDumperStatus_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response, _impl_.error_),
  PROTOBUF_FIELD_OFFSET(::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response, _impl_.active_),
  ~0u,
  0,
  ~0u,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::com::wazuh::api::engine::event_dumper::EventDumperActivate_Request)},
  { 6, -1, -1, sizeof(::com::wazuh::api::engine::event_dumper::EventDumperDeactivate_Request)},
  { 12, -1, -1, sizeof(::com::wazuh::api::engine::event_dumper::EventDumperStatus_Request)},
  { 18, 27, -1, sizeof(::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::com::wazuh::api::engine::event_dumper::_EventDumperActivate_Request_default_instance_._instance,
  &::com::wazuh::api::engine::event_dumper::_EventDumperDeactivate_Request_default_instance_._instance,
  &::com::wazuh::api::engine::event_dumper::_EventDumperStatus_Request_default_instance_._instance,
  &::com::wazuh::api::engine::event_dumper::_EventDumperStatus_Response_default_instance_._instance,
};

const char descriptor_table_protodef_event_5fdumper_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022event_dumper.proto\022!com.wazuh.api.engi"
  "ne.event_dumper\032\014engine.proto\"\035\n\033EventDu"
  "mperActivate_Request\"\037\n\035EventDumperDeact"
  "ivate_Request\"\033\n\031EventDumperStatus_Reque"
  "st\"~\n\032EventDumperStatus_Response\0222\n\006stat"
  "us\030\001 \001(\0162\".com.wazuh.api.engine.ReturnSt"
  "atus\022\022\n\005error\030\002 \001(\tH\000\210\001\001\022\016\n\006active\030\003 \001(\010"
  "B\010\n\006_errorb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_event_5fdumper_2eproto_deps[1] = {
  &::descriptor_table_engine_2eproto,
};
static ::_pbi::once_flag descriptor_table_event_5fdumper_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_event_5fdumper_2eproto = {
    false, false, 298, descriptor_table_protodef_event_5fdumper_2eproto,
    "event_dumper.proto",
    &descriptor_table_event_5fdumper_2eproto_once, descriptor_table_event_5fdumper_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_event_5fdumper_2eproto::offsets,
    file_level_metadata_event_5fdumper_2eproto, file_level_enum_descriptors_event_5fdumper_2eproto,
    file_level_service_descriptors_event_5fdumper_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_event_5fdumper_2eproto_getter() {
  return &descriptor_table_event_5fdumper_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_event_5fdumper_2eproto(&descriptor_table_event_5fdumper_2eproto);
namespace com {
namespace wazuh {
namespace api {
namespace engine {
namespace event_dumper {

// ===================================================================

class EventDumperActivate_Request::_Internal {
 public:
};

EventDumperActivate_Request::EventDumperActivate_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:com.wazuh.api.engine.event_dumper.EventDumperActivate_Request)
}
EventDumperActivate_Request::EventDumperActivate_Request(const EventDumperActivate_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  EventDumperActivate_Request* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.wazuh.api.engine.event_dumper.EventDumperActivate_Request)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EventDumperActivate_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EventDumperActivate_Request::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata EventDumperActivate_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_event_5fdumper_2eproto_getter, &descriptor_table_event_5fdumper_2eproto_once,
      file_level_metadata_event_5fdumper_2eproto[0]);
}

// ===================================================================

class EventDumperDeactivate_Request::_Internal {
 public:
};

EventDumperDeactivate_Request::EventDumperDeactivate_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:com.wazuh.api.engine.event_dumper.EventDumperDeactivate_Request)
}
EventDumperDeactivate_Request::EventDumperDeactivate_Request(const EventDumperDeactivate_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  EventDumperDeactivate_Request* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.wazuh.api.engine.event_dumper.EventDumperDeactivate_Request)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EventDumperDeactivate_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EventDumperDeactivate_Request::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata EventDumperDeactivate_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_event_5fdumper_2eproto_getter, &descriptor_table_event_5fdumper_2eproto_once,
      file_level_metadata_event_5fdumper_2eproto[1]);
}

// ===================================================================

class EventDumperStatus_Request::_Internal {
 public:
};

EventDumperStatus_Request::EventDumperStatus_Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:com.wazuh.api.engine.event_dumper.EventDumperStatus_Request)
}
EventDumperStatus_Request::EventDumperStatus_Request(const EventDumperStatus_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  EventDumperStatus_Request* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:com.wazuh.api.engine.event_dumper.EventDumperStatus_Request)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EventDumperStatus_Request::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EventDumperStatus_Request::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata EventDumperStatus_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_event_5fdumper_2eproto_getter, &descriptor_table_event_5fdumper_2eproto_once,
      file_level_metadata_event_5fdumper_2eproto[2]);
}

// ===================================================================

class EventDumperStatus_Response::_Internal {
 public:
  using HasBits = decltype(std::declval<EventDumperStatus_Response>()._impl_._has_bits_);
  static void set_has_error(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

EventDumperStatus_Response::EventDumperStatus_Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
}
EventDumperStatus_Response::EventDumperStatus_Response(const EventDumperStatus_Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  EventDumperStatus_Response* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.error_){}
    , decltype(_impl_.status_){}
    , decltype(_impl_.active_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_error()) {
    _this->_impl_.error_.Set(from._internal_error(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.status_, &from._impl_.status_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.active_) -
    reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.active_));
  // @@protoc_insertion_point(copy_constructor:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
}

inline void EventDumperStatus_Response::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.error_){}
    , decltype(_impl_.status_){0}
    , decltype(_impl_.active_){false}
  };
  _impl_.error_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

EventDumperStatus_Response::~EventDumperStatus_Response() {
  // @@protoc_insertion_point(destructor:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void EventDumperStatus_Response::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_.Destroy();
}

void EventDumperStatus_Response::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void EventDumperStatus_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.error_.ClearNonDefaultToEmpty();
  }
  ::memset(&_impl_.status_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.active_) -
      reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.active_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* EventDumperStatus_Response::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .com.wazuh.api.engine.ReturnStatus status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::com::wazuh::api::engine::ReturnStatus>(val));
        } else
          goto handle_unusual;
        continue;
      // optional string error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "com.wazuh.api.engine.event_dumper.EventDumperStatus_Response.error"));
        } else
          goto handle_unusual;
        continue;
      // bool active = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.active_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* EventDumperStatus_Response::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .com.wazuh.api.engine.ReturnStatus status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // optional string error = 2;
  if (_internal_has_error()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error().data(), static_cast<int>(this->_internal_error().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.wazuh.api.engine.event_dumper.EventDumperStatus_Response.error");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error(), target);
  }

  // bool active = 3;
  if (this->_internal_active() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_active(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
  return target;
}

size_t EventDumperStatus_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional string error = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error());
  }

  // .com.wazuh.api.engine.ReturnStatus status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  // bool active = 3;
  if (this->_internal_active() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EventDumperStatus_Response::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    EventDumperStatus_Response::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EventDumperStatus_Response::GetClassData() const { return &_class_data_; }


void EventDumperStatus_Response::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<EventDumperStatus_Response*>(&to_msg);
  auto& from = static_cast<const EventDumperStatus_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_error()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  if (from._internal_active() != 0) {
    _this->_internal_set_active(from._internal_active());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void EventDumperStatus_Response::CopyFrom(const EventDumperStatus_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.wazuh.api.engine.event_dumper.EventDumperStatus_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EventDumperStatus_Response::IsInitialized() const {
  return true;
}

void EventDumperStatus_Response::InternalSwap(EventDumperStatus_Response* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_, lhs_arena,
      &other->_impl_.error_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EventDumperStatus_Response, _impl_.active_)
      + sizeof(EventDumperStatus_Response::_impl_.active_)
      - PROTOBUF_FIELD_OFFSET(EventDumperStatus_Response, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::PROTOBUF_NAMESPACE_ID::Metadata EventDumperStatus_Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_event_5fdumper_2eproto_getter, &descriptor_table_event_5fdumper_2eproto_once,
      file_level_metadata_event_5fdumper_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace event_dumper
}  // namespace engine
}  // namespace api
}  // namespace wazuh
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::wazuh::api::engine::event_dumper::EventDumperActivate_Request*
Arena::CreateMaybeMessage< ::com::wazuh::api::engine::event_dumper::EventDumperActivate_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::wazuh::api::engine::event_dumper::EventDumperActivate_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::com::wazuh::api::engine::event_dumper::EventDumperDeactivate_Request*
Arena::CreateMaybeMessage< ::com::wazuh::api::engine::event_dumper::EventDumperDeactivate_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::wazuh::api::engine::event_dumper::EventDumperDeactivate_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::com::wazuh::api::engine::event_dumper::EventDumperStatus_Request*
Arena::CreateMaybeMessage< ::com::wazuh::api::engine::event_dumper::EventDumperStatus_Request >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::wazuh::api::engine::event_dumper::EventDumperStatus_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response*
Arena::CreateMaybeMessage< ::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::wazuh::api::engine::event_dumper::EventDumperStatus_Response >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
