#!/usr/bin/env expect

# Agentless monitoring
#
# Copyright (C) 2015-2019, Wazuh Inc.
# Copyright (C) 2009 Trend Micro Inc.
# All rights reserved.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

if {[string compare $pass "NOPASS"] == 0} {
    source $sshnopasssrc
    return
}

expect {
    "WARNING: REMOTE HOST" {
        send_user "\nERROR: RSA host key for '$hostname' has changed. Unable to access.\n"
        exit 1;
    }
    "*sure you want to continue connecting*" {
        send "yes\r"
        expect "*assword:*" {
            send "$pass\r"
            source $sshloginsrc
        }
    }
    "ssh: connect to host*" {
        send_user "\nERROR: Unable to connect to remote host: $hostname .\n"
        exit 1;
    }
    "no address associated with name" {
        send_user "\nERROR: Unable to connect to remote host: $hostname .\n"
        exit 1;
    }
    "*Connection refused*" {
        send_user "\nERROR: Unable to connect to remote host: $hostname .\n"
        exit 1;
    }
    "*Connection closed by remote host*" {
        send_user "\nERROR: Unable to connect to remote host: $hostname .\n"
        exit 1;
    }
    "*assword:*" {
        send "$pass\r"
        source $sshloginsrc
    }
    timeout {
        send_user "\nERROR: Timeout while connecting to host: $hostname . \n"
        exit 1;
    }
}
