#!/usr/bin/env expect

# Agentless monitoring
#
# Copyright (C) 2009 Trend Micro Inc.
# All rights reserved.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

expect {
    "Permission denied" {
        send_user "\nERROR: Incorrect password to remote host: $hostname .\n"
        exit 1;
    }
    eof {
        send_user "\nERROR: EOF while logging to host: $hostname .\n"
        exit 0;
    }
    timeout {
        send_user "\nERROR: Timeout while running on host: $hostname .\n"
        exit 1;
    }
    "*\\\$" {
        send_user "\nINFO: Started.\n"
    }
    "*#" {
        send_user "\nINFO: Started.\n"
    }
}
