#!/usr/bin/env expect


expect {
    "Permission denied" {
        send_user "ERROR: Incorrect password to remote host: $hostname .\n"
        exit 1;
    }
    eof {
        send_user "ERROR: EOF while logging to host: $hostname .\n"
        exit 0;
    }
    timeout {
        send_user "ERROR: Timeout while running on host: $hostname .\n"
        exit 1;
    }
    "*\\\$" {
        send_user "\nINFO: Started.\n"
    }
    "*#" {
        send_user "\nINFO: Started.\n"
    }
}
