#!/usr/bin/env expect

# Agentless monitoring
#
# Copyright (C) 2015-2019, Wazuh Inc.
# Copyright (C) 2009 Trend Micro Inc.
# All rights reserved.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# If su was chosen
set timeout 10
if {[string compare $use_su "su;"] == 0} {

    # Run su command
    send "\rsu\r"

    expect {
        "Password:" {
            send "$addpass\r"
        }
        timeout {
            send_user "\nERROR: Unable to run su.\n"
            exit 1;
        }
    }

    expect {
        "Permission denied" {
            send_user "\nERROR: Incorrect su password to host: $hostname .\n"
            exit 1;
        }
        "Password:" {
            send_user "\nERROR: Incorrect su password to host: $hostname .\n"
            exit 1;
        }
        "Sorry" {
            send_user "\nERROR: Incorrect su password to remote host: $hostname .\n"
            exit 1;
        }
        eof {
            send_user "\nERROR: EOF while running su on host: $hostname .\n"
            exit 1;
        }
        timeout {
            send_user "\nERROR: Timeout while running on host: $hostname .\n"
            exit 1;
        }
        "*#" {
            send_user "\nINFO: su accepted.\n"
        }
    }
}
