#!/bin/sh

# Copyright (C) 2015-2020, Wazuh Inc.
# March 6, 2019.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Load ossec-init variables
# . /etc/ossec-init.conf

# Global variables
CONF_FILE="${DIRECTORY}/etc/ossec.conf"
TMP_ENROLLMENT="${DIRECTORY}/tmp/autoenrollment.conf"

# Init variables to empty string
WAZUH_MANAGER=""
WAZUH_MANAGER_PORT=""
WAZUH_PROTOCOL=""
WAZUH_REGISTRATION_SERVER=""
WAZUH_REGISTRATION_PORT=""
WAZUH_REGISTRATION_PASSWORD=""
WAZUH_KEEP_ALIVE_INTERVAL=""
WAZUH_TIME_RECONNECT=""
WAZUH_REGISTRATION_CA=""
WAZUH_REGISTRATION_CERTIFICATE=""
WAZUH_REGISTRATION_KEY=""
WAZUH_AGENT_NAME=""
WAZUH_AGENT_GROUP=""

# Set default sed alias
sed="sed -ri"
# By default, use gnu sed (gsed).
use_unix_sed="False"

# Special function to use generic sed
unix_sed() {
    sed_expression="$1"
    target_file="$2"
    special_args="$3"

    sed ${special_args} ${sed_expression} ${target_file} > ${target_file}.tmp
    cat "${target_file}.tmp" > "${target_file}"
    rm "${target_file}.tmp"
}

# Update the value of a XML tag inside the ossec.conf
edit_value_tag() {

    file=""

    if [ -z "$3" ]; then
        file="${CONF_FILE}"
    else
        file="${TMP_ENROLLMENT}"
    fi

    if [ ! -z "$1" ] && [ ! -z "$2" ]; then
        start_config="$(grep -n "<$1>" ${file} | cut -d':' -f 1)"
        end_config="$(grep -n "</$1>" ${file} | cut -d':' -f 1)"
        if [ ! -n "${start_config}" ] && [ ! -n "${end_config}" ] && [ "${file}" = "${TMP_ENROLLMENT}" ]; then
            echo "      <$1>$2</$1>" >> ${file}
        elif [ "${use_unix_sed}" = "False" ] ; then
            ${sed} "s#<$1>.*</$1>#<$1>$2</$1>#g" "${file}"
        else
            unix_sed "s#<$1>.*</$1>#<$1>$2</$1>#g" "${file}"
        fi
    fi
}

delete_blank_lines() {
    file=$1
    if [ "${use_unix_sed}" = "False" ] ; then
        ${sed} '/^$/d' "${file}"
    else
        unix_sed '/^$/d' "${file}"
    fi
}
delete_auto_enrollment_tag() {
    # Delete the configuration tag if its value is empty
    # This will allow using the default value
    if [ "${use_unix_sed}" = "False" ] ; then
        ${sed} "s#.*<$1>.*</$1>.*##g" "${TMP_ENROLLMENT}"
    else
        unix_sed "s#.*<$1>.*</$1>.*##g" "${TMP_ENROLLMENT}"
    fi

    cat -s "${TMP_ENROLLMENT}" > "${TMP_ENROLLMENT}.tmp"
    mv "${TMP_ENROLLMENT}.tmp" "${TMP_ENROLLMENT}"
}

# Change address block of the ossec.conf
add_adress_block() {
    # Getting function parameters on new variable
    SET_ADDRESSES="$@"

    # Remove the server configuration
    if [ "${use_unix_sed}" = "False" ] ; then
        ${sed} "/<server>/,/\/server>/d" ${CONF_FILE}
    else
        unix_sed "/<server>/,/\/server>/d" "${CONF_FILE}"
    fi

    # Get the client configuration generated by gen_ossec.sh
    start_config="$(grep -n "<client>" ${CONF_FILE} | head -n 1 | cut -d':' -f 1)"
    end_config="$(grep -n "</client>" ${CONF_FILE} | head -n 1 | cut -d':' -f 1)"
    start_config=$(( start_config + 1 ))
    end_config=$(( end_config - 1 ))
    client_config="$(sed -n "${start_config},${end_config}p" ${CONF_FILE})"

    # Remove the client configuration
    if [ "${use_unix_sed}" = "False" ] ; then
        ${sed} "/<client>/,/\/client>/d" ${CONF_FILE}
    else
        unix_sed "/<client>/,/\/client>/d" "${CONF_FILE}"
    fi

    # Write the client configuration block
    echo "<ossec_config>" >> ${CONF_FILE}
    echo "  <client>" >> ${CONF_FILE}
    for i in ${SET_ADDRESSES};
    do
        echo "    <server>" >> ${CONF_FILE}
        echo "      <address>$i</address>" >> ${CONF_FILE}
        echo "      <port>1514</port>" >> ${CONF_FILE}
        echo "      <protocol>udp</protocol>" >> ${CONF_FILE}
        echo "    </server>" >> ${CONF_FILE}
    done

    echo "${client_config}" >> ${CONF_FILE}
    echo "  </client>" >> ${CONF_FILE}
    echo "</ossec_config>" >> ${CONF_FILE}
}

# Function to convert strings to lower version
tolower () {
   echo $1 | tr '[:upper:]' '[:lower:]'
}


# Add auto-enrollment configuration block
add_auto_enrollment () {
    start_config="$(grep -n "<auto_enrollment>" ${DIRECTORY}/etc/ossec.conf | cut -d':' -f 1)"
    end_config="$(grep -n "</auto_enrollment>" ${DIRECTORY}/etc/ossec.conf | cut -d':' -f 1)"
    if [ -n "${start_config}" ] && [ -n "${end_config}" ]; then
        start_config=$(( start_config + 1 ))
        end_config=$(( end_config - 1 ))
        sed -n "${start_config},${end_config}p" ${DIRECTORY}/etc/ossec.conf >> "${TMP_ENROLLMENT}"
    else
        # Write the client configuration block
        echo "<ossec_config>" >> "${TMP_ENROLLMENT}"
        echo "  <client>" >> "${TMP_ENROLLMENT}"
        echo "    <enrollment>" >> "${TMP_ENROLLMENT}"
        echo "      <enabled>yes</enabled>" >> "${TMP_ENROLLMENT}"
        echo "      <auto_method>no</auto_method>" >> "${TMP_ENROLLMENT}"
        echo "      <use_source_ip>no</use_source_ip>" >> "${TMP_ENROLLMENT}"
        echo "      <delay_after_enrollment>20</delay_after_enrollment>" >> "${TMP_ENROLLMENT}"
        echo "      <ssl_cipher>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ssl_cipher>" >> "${TMP_ENROLLMENT}"
        echo "      <manager_address>MANAGER_IP</manager_address>" >> "${TMP_ENROLLMENT}"
        echo "      <port>1515</port>" >> "${TMP_ENROLLMENT}"
        echo "      <agent_name>agent</agent_name>" >> "${TMP_ENROLLMENT}"
        echo "      <groups>Group1</groups>" >> "${TMP_ENROLLMENT}"
        echo "      <server_ca_path>/path/to/server_ca</server_ca_path>" >> "${TMP_ENROLLMENT}"
        echo "      <agent_certificate_path>/path/to/agent.cert</agent_certificate_path>" >> "${TMP_ENROLLMENT}"
        echo "      <agent_key_path>/path/to/agent.key</agent_key_path>" >> "${TMP_ENROLLMENT}"
        echo "      <authorization_pass>TopSecret</authorization_pass>" >> "${TMP_ENROLLMENT}"
        echo "    </enrollment>" >> "${TMP_ENROLLMENT}"
        echo "  </client>" >> "${TMP_ENROLLMENT}"
        echo "</ossec_config>" >> "${TMP_ENROLLMENT}"
    fi
}

# Add the auto_enrollment block to the configuration file
concat_conf(){
    start_config="$(grep -n "<auto_enrollment>" ${DIRECTORY}/etc/ossec.conf | cut -d':' -f 1)"
    end_config="$(grep -n "</auto_enrollment>" ${DIRECTORY}/etc/ossec.conf | cut -d':' -f 1)"
    if [ -n "${start_config}" ] && [ -n "${end_config}" ]; then
        # Remove the server configuration
        if [ "${use_unix_sed}" = "False" ] ; then
            ${sed} -e "/<auto_enrollment>/,/<\/auto_enrollment>/{ /<auto_enrollment>/{p; r ${TMP_ENROLLMENT}
            }; /<\/auto_enrollment>/p; d }" ${CONF_FILE}
        else
            unix_sed "/<auto_enrollment>/,/<\/auto_enrollment>/{ /<auto_enrollment>/{p; r ${TMP_ENROLLMENT}
            }; /<\/auto_enrollment>/p; d }" "${CONF_FILE}" "-e"
        fi
    else
        cat ${TMP_ENROLLMENT} >> ${CONF_FILE}
    fi

    rm -f ${TMP_ENROLLMENT}
}

# Set autoenrollment configuration
set_auto_enrollment_tag_value () {
    tag="$1"
    value="$2"

    if [ ! -z "${value}" ]; then
        edit_value_tag "${tag}" ${value} "auto_enrollment"
    else
        delete_auto_enrollment_tag "${tag}" "auto_enrollment"
    fi
}

help () {
    case "$1" in
        "enroll")
            echo
            echo "Usage: $0 enroll <options>"
            echo
            echo "    --address                               [Optional] Wazuh manager address"
            echo "    --port                                  [Optional] Wazuh manager port"
            echo "    --protocol                              [Optional] Wazuh manager protocol"
            echo "    --registration-address                  [Optional] Wazuh registration address"
            echo "    --registration-port                     [Optional] Wazuh registration port"
            echo "    --token                                 [Optional] Wazuh registration password"
            echo "    --keep-alive                            [Optional] Wazuh agent keep alive time"
            echo "    --reconnection-time                     [Optional] Wazuh agent reconnection time"
            echo "    --registration-ca                       [Optional] Certification Authority (CA) path"
            echo "    --registration-certificate              [Optional] Registration certificate path"
            echo "    --registration-key                      [Optional] Registration key path"
            echo "    --name                                  [Optional] Wazuh agent name"
            echo "    --group                                 [Optional] Wazuh agent group"
            echo "    help                                    Show this help."
            echo
            ;;
        "help")
            echo
            echo "Usage: $0 <command> <options>"
            echo
            echo "To see help text, you can run:"
            echo "    wazuhctl help"
            echo "    wazuhctl enroll help"
            echo
            ;;
        esac
    exit 1
}

# Main function the script begin here
main () {
    uname_s=$(uname -s)

    # Check what kind of system we are working with
    if [ "${uname_s}" = "Darwin" ]; then
        sed="sed -ire"
    elif [ "${uname_s}" = "AIX" ] || [ "${uname_s}" = "SunOS" ] || [ "${uname_s}" = "HP-UX" ]; then
        use_unix_sed="True"
    fi

    case "$1" in
        "help")
            help "help"
            ;;
        "enroll")
            shift 1
            while [ -n "$1" ]
            do
                case "$1" in
                "help")
                        help "enroll"
                    ;;
                "--address")
                    if [ -n "$2" ]; then
                        WAZUH_MANAGER="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--port")
                    if [ -n "$2" ]; then
                        WAZUH_MANAGER_PORT="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--protocol")
                    if [ -n "$2" ]; then
                    WAZUH_PROTOCOL="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--registration-address")
                    if [ -n "$2" ]; then
                        WAZUH_REGISTRATION_SERVER="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--registration-port")
                    if [ -n "$2" ]; then
                        WAZUH_REGISTRATION_PORT="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--token")
                    if [ -n "$2" ]; then
                        WAZUH_REGISTRATION_PASSWORD="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--keep-alive")
                    if [ -n "$2" ]; then
                        WAZUH_KEEP_ALIVE_INTERVAL="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--reconnection-time")
                    if [ -n "$2" ]; then
                        WAZUH_TIME_RECONNECT="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--registration-ca")
                    if [ -n "$2" ]; then
                        WAZUH_REGISTRATION_CA="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--registration-certificate")
                    if [ -n "$2" ]; then
                        WAZUH_REGISTRATION_CERTIFICATE="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--registration-key")
                    if [ -n "$2" ]; then
                        WAZUH_REGISTRATION_KEY="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--name")
                    if [ -n "$2" ]; then
                        WAZUH_AGENT_NAME="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                "--group")
                    if [ -n "$2" ]; then
                        WAZUH_AGENT_GROUP="$2"
                        shift 2
                    else
                        shift 1
                    fi
                    ;;
                *)
                    help "enroll"
                esac
            done
            ;;
        *)
            help "help"
            ;;
    esac

    if [ ! -z ${WAZUH_MANAGER} ]; then
        if [ ! -f ${DIRECTORY}/logs/ossec.log ]; then
            touch -f ${DIRECTORY}/logs/ossec.log
            chmod 660 ${DIRECTORY}/logs/ossec.log
            chown root:ossec ${DIRECTORY}/logs/ossec.log
        fi

        # Check if multiples IPs are defined in variable WAZUH_MANAGER
        WAZUH_MANAGER=$(echo ${WAZUH_MANAGER} | sed "s#,#;#g")
        ADDRESSES="$(echo ${WAZUH_MANAGER} | awk '{split($0,a,";")} END{ for (i in a) { print a[i] } }' |  tr '\n' ' ')"
        if echo ${ADDRESSES} | grep ' ' > /dev/null 2>&1 ; then
            # Get uniques values
            ADDRESSES=$(echo "${ADDRESSES}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
            add_adress_block "${ADDRESSES}"
            WAZUH_REGISTRATION_SERVER="$(echo $ADDRESSES | cut -d ' ' -f 1)"
        else
            # Single address
            edit_value_tag "address" ${WAZUH_MANAGER}
            WAZUH_REGISTRATION_SERVER="${WAZUH_MANAGER}"
        fi

        # Options to be modified in ossec.conf
        edit_value_tag "protocol" "$(tolower ${WAZUH_PROTOCOL})"
        edit_value_tag "port" ${WAZUH_MANAGER_PORT}
        edit_value_tag "notify_time" ${WAZUH_KEEP_ALIVE_INTERVAL}
        edit_value_tag "time-reconnect" ${WAZUH_TIME_RECONNECT}

        add_auto_enrollment
        set_auto_enrollment_tag_value "manager_address" ${WAZUH_REGISTRATION_SERVER}
        set_auto_enrollment_tag_value "port" ${WAZUH_REGISTRATION_PORT}
        set_auto_enrollment_tag_value "authorization_pass" ${WAZUH_REGISTRATION_PASSWORD}
        set_auto_enrollment_tag_value "server_ca_path" ${WAZUH_REGISTRATION_CA}
        set_auto_enrollment_tag_value "agent_certificate_path" ${WAZUH_REGISTRATION_CERTIFICATE}
        set_auto_enrollment_tag_value "agent_key_path" ${WAZUH_REGISTRATION_KEY}
        set_auto_enrollment_tag_value "agent_name" ${WAZUH_AGENT_NAME}
        set_auto_enrollment_tag_value "groups" ${WAZUH_AGENT_GROUP}
        delete_blank_lines ${TMP_ENROLLMENT}
        concat_conf
    fi
}

# Start script execution
main "$@"
