@startwbs
+ wazuh
 + init
 + api
 + etc
 + extensions
 + framework
 + integrations
 + ruleset
 + installer
  + win32
 + src
  + active_response
   + scripts
    +_ restart.sh
   + restart
    + src
    +_ CMakeList.txt
   +_ CMakeLists.txt
  + config
   + src
   + include
   +_ CMakeLists.txt
  + common
   + error_messages
   + wazuhext
    +_ CMakeLists.txt
    +_ empty.cpp
  + utils
   + xml
    + include
    + src
    +_ CMakeLists.txt
   + crypto
    + include
    + src
    +_ CMakeLists.txt
   + net
    + include
    + src
    +_ CMakeLists.txt
   + regex
    + include
    + src
    + testtool
    +_ CMakeLists.txt
   + data_provider
    + include
    + src
    + tests
    + testtool
    +_ CMakeLists.txt
   + zlib
    + src
    + include
    +_ CMakeLists.txt
   + rsync
    + include
    + src
    + tests
    + testtool
    +_ CMakeLists.txt
   + dbsync
    + include
    + src
    + tests
    + testtool
    +_ CMakeLists.txt
   +_ CMakeLists.txt
  + agent
   + common
    + include
   + sensors
    + common
     + include
     +_ CMakeLists.txt
    + helpers
     + src
     + include
     +_ CMakeLists.txt
    + aws
     + src
     + include
     +_ CMakeLists.txt
    + docker
     + src
     + include
     +_ CMakeLists.txt
    + syscollector
     + src
     + include
     +_ CMakeLists.txt
    + syscheck
     + src
     + include
     +_ CMakeLists.txt
    + rootcheck
     + src
     + include
    +_ CMakeLists.txt
    +_ main.c
   +_ CMakeLists.txt
  + manager
   + common
    +_ CMakeLists.txt
   + core
    + integrator
     + include
     + src
     +_ CMakeLists.txt
    + agentless
     + include
     + src
     + scripts
     +_ CMakeLists.txt
    + monitor
     + include
     + src
     +_ CMakeLists.txt
    + vulnerability_detector
     + include
     + src
     +_ CMakeLists.txt
    + mail
     + include
     + src
    +_ main.c
    +_ CMakeLists.txt
   + analysis
    + decoders
    +_ main.c
    +_ CMakeLists.txt
   + remote
    + include
    + src
    +_ main.c
    +_ CMakeLists.txt
   + wazuh-db
    + include
    + src
    +_ main.c
    +_ CMakeLists.txt
   +_ CMakeLists.txt
  +_ CMakeLists.txt
@endwbs