kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: wazuh-spike
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        containerLogMaxSize: "1Mi"
        containerLogMaxFiles: 3
        maxPods: 150
