run-name: Package - Upload pkg_${{ inputs.system }}_manager_builder_${{ inputs.architecture }} with tag ${{ inputs.docker_image_tag }}
name: 4.X - Package - Upload manager images

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: |
          Tag name of the Docker image to be uploaded.
          Use 'developer' to set branch name as tag.
          Use 'auto' to set branch version as tag.
          If using a custom tag, use only '-', '_', '.' and alphanumeric characters.
          Default is 'auto'.
        required: false
        default: auto
      architecture:
        description: |
          Architecture of the package [amd64, arm64]
        type: choice
        options:
          - amd64
          - arm64
        required: true
      system:
        type: choice
        description: |
          System image to upload [deb, rpm].
        options:
          - deb
          - rpm
      source_reference:
        description: |
          Branch from wazuh/wazuh repository to use.
        required: true

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - name: Warning
        run: echo "This workflow is deprecated. Be careful, you have just run it from main."
