run-name: Package 4.X - Upload Docker package building images
name: 4.X - Package - Upload Docker package building images

on:
  push:
    branches:
      - "[0-4].[0-9]+.[0-9]+"
    paths:
      - "packages/**"

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - name: Warning
        run: echo "This workflow is deprecated. Be careful, you have just run it from main."
