name: 4.X - Coverity Docker image - Create and publish

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: |
          Tag name of the Docker image to be uploaded.
          Use only '-', '_', '.' and alphanumeric characters.
          Default is '4.x'.
        required: false
        default: "4.x"
  push:
    paths:
      - "tools/testing/coverity/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wazuh/coverity-scan

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - name: Warning
        run: echo "This workflow is deprecated. Be careful, you have just run it from main."
