name: 4.X - Code Linter - ClangFormat

on:
  workflow_dispatch:
  pull_request:
    # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]

permissions:
  id-token: write
  contents: read

jobs:
  style:
    runs-on: codebuild-github-actions-codebuild-runner-server-amd-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Inventory harvester - Coding style
        uses: ./.github/actions/clang_format
        with:
          bucket: ${{ secrets.CI_INTERNAL_S3_BUCKET }}
          aws_role: ${{ secrets.CI_OIDC_ROLE_ARN }}
          path: src/wazuh_modules/inventory_harvester
