name: 4.X - Create and publish - Unit tests Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "[0-4].[0-9]+.[0-9]+"
    paths:
      - "tools/testing/unit-tests/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wazuh/unit-tests

jobs:
  deprecated:
    runs-on: ubuntu-24.04
    steps:
      - name: Warning
        run: echo "This workflow is deprecated. Be careful, you have just run it from main."
