name: 5.X - Build Binutils Packages

on:
  workflow_dispatch:
    inputs:
      binutils_major_version:
        description: "Binutils major version"
        required: true
        default: "2"
      binutils_minor_version:
        description: "Binutils minor version"
        required: true
        default: "38"

jobs:
  build-package:
    runs-on: ${{ matrix.arch == 'amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    name: Build ${{ matrix.system }} (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        system: [deb, rpm]
        arch: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Docker build
        run: |
          IMAGE_NAME="binutils-${{ matrix.system }}-${{ matrix.arch }}"
          docker build -t $IMAGE_NAME -f packages/${{ matrix.system }}s/${{ matrix.arch }}/binutils/Dockerfile \
            --build-arg BINUTILS_MAJOR_VERSION=${{ inputs.binutils_major_version }} \
            --build-arg BINUTILS_MINOR_VERSION=${{ inputs.binutils_minor_version }} .
          docker run -v /tmp:/tmp $IMAGE_NAME /bin/bash -c "cp /packages/* /tmp/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binutils-${{ matrix.system }}-${{ matrix.arch }}
          path: /tmp/*.${{ matrix.system }}
