run-name: Package 5.X - Upload Docker package building images
name: 5.X - Package - Upload Docker package building images

on:
  push:
    branches:
      - "5.[0-9]+.[0-9]+"
      - "main"
    paths:
      - "packages/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  detect-changes:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: "false"

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get changed files
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            pkg_deb_manager_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/amd64/manager/**'
              - 'packages/debs/utils/**'
            pkg_deb_manager_builder_arm64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/arm64/manager/**'
              - 'packages/debs/utils/**'
            pkg_rpm_manager_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/amd64/manager/**'
              - 'packages/rpms/utils/**'
            pkg_rpm_manager_builder_arm64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/arm64/manager/**'
              - 'packages/rpms/utils/**'
            pkg_deb_agent_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/amd64/agent/**'
              - 'packages/debs/utils/**'
            pkg_rpm_agent_builder_amd64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/amd64/agent/**'
              - 'packages/rpms/utils/**'
            pkg_deb_agent_builder_arm64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/debs/arm64/agent/**'
              - 'packages/debs/utils/**'
            pkg_rpm_agent_builder_arm64:
              - 'packages/build.sh'
              - 'packages/generate_package.sh'
              - 'packages/rpms/arm64/agent/**'
              - 'packages/rpms/utils/**'
            compile_windows_agent:
              - 'packages/windows/**'
            commom_wpk_builder:
              - 'packages/wpk/wpkpack.py'
              - 'packages/wpk/run.sh'
              - 'packages/wpk/generate_wpk_package.sh'
              - 'packages/wpk/common/**'

      - name: Get tag
        id: set-tag
        run: |
          VERSION="$(grep '"version"' VERSION.json | sed -E 's/.*"version": *"([^"]+)".*/\1/')"
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

  trigger-workflows:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.changes != '[]' }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - key: pkg_deb_manager_builder_amd64
            repo: current
            workflow: 5_builderprecompiled_docker-images-upload-manager.yml
            arch: amd64
            system: deb
          - key: pkg_rpm_manager_builder_amd64
            repo: current
            workflow: 5_builderprecompiled_docker-images-upload-manager.yml
            arch: amd64
            system: rpm
          - key: pkg_deb_manager_builder_arm64
            repo: current
            workflow: 5_builderprecompiled_docker-images-upload-manager.yml
            arch: arm64
            system: deb
          - key: pkg_rpm_manager_builder_arm64
            repo: current
            workflow: 5_builderprecompiled_docker-images-upload-manager.yml
            arch: arm64
            system: rpm
          - key: pkg_deb_agent_builder_amd64
            repo: wazuh/wazuh-agent-packages
            workflow: 5_builderpackage_upload-images-amd.yml
            arch: amd64
            system: deb
          - key: pkg_rpm_agent_builder_amd64
            repo: wazuh/wazuh-agent-packages
            workflow: 5_builderpackage_upload-images-amd.yml
            arch: amd64
            system: rpm
          - key: pkg_deb_agent_builder_arm64
            repo: wazuh/wazuh-agent-packages
            workflow: 5_builderpackage_upload-images-arm.yml
            arch: arm64
            system: deb
          - key: pkg_rpm_agent_builder_arm64
            repo: wazuh/wazuh-agent-packages
            workflow: 5_builderpackage_upload-images-arm.yml
            arch: arm64
            system: rpm
          - key: compile_windows_agent
            repo: wazuh/wazuh-agent-packages
            workflow: 5_builderpackage_upload-images-amd.yml
            arch: i386
            system: windows
          - key: commom_wpk_builder
            repo: wazuh/wazuh-agent-packages
            workflow: 5_builderpackage_upload-images-wpk.yml

    steps:
      - name: Request update for ${{ matrix.key }}
        if: contains(fromJSON(needs.detect-changes.outputs.changes), matrix.key)
        run: |
          CMD="gh workflow run ${{ matrix.workflow }} -r ${{ github.ref_name }} -f docker_image_tag=${{ needs.detect-changes.outputs.tag }} -f source_reference=${{ github.ref_name }}"
          if [ "${{ matrix.repo }}" != "current" ]; then CMD="$CMD --repo ${{ matrix.repo }}"; fi
          if [ -n "${{ matrix.arch }}" ]; then CMD="$CMD -f architecture=${{ matrix.arch }}"; fi
          if [ -n "${{ matrix.system }}" ]; then CMD="$CMD -f system=${{ matrix.system }}"; fi
          eval $CMD
        env:
          GH_TOKEN: ${{ matrix.repo == 'current' && secrets.GITHUB_TOKEN || secrets.CI_WAZUH_AGENT_PACKAGES }}

