run-name: Build Wazuh agent macOS - ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }} - ${{ inputs.architecture || 'intel64,arm64' }}
name: 5.X - Build Wazuh agent macOS (PKG)

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - "src/**"
      - "packages/**"
      - ".github/workflows/5_builderpackage_agent-macos.yml"
  workflow_dispatch:
    inputs:
      architecture:
        type: choice
        description: Package architecture [intel64, arm64].
        required: true
        default: intel64
        options:
          - intel64
          - arm64
      revision:
        description: |
          Package revision (name and metadata).
          Default is '1'.
        required: false
        default: '1'
      debug:
        type: boolean
        description: |
          Build the binaries as debug (without optimizations).
          Default is 'false'.
        required: false
        default: false
      checksum:
        type: boolean
        description: |
          Generate package checksum.
          Default is 'false'.
        required: false
        default: false

jobs:
  build-macos:
    if: github.event_name == 'pull_request' || inputs.architecture == matrix.arch
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: intel64
            runner: macos-14-large
          - arch: arm64
            runner: macos-14
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 90
    name: Build PKG package (${{ matrix.arch }})
    outputs:
      package-name: ${{ steps.build.outputs.package-name }}
      package-symbols-name: ${{ steps.build.outputs.package-symbols-name }}
      version: ${{ steps.build.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set VERSION and append commit
        run: |
          VERSION="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' VERSION.json)"
          [ -n "$VERSION" ] || exit 1
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          SHORT_COMMIT=$(git rev-parse --short=7 HEAD)
          [ -n "$SHORT_COMMIT" ] || exit 1
          sed -i '' '/"stage":/s/$/,/; /}/{i\
              "commit": "'"$SHORT_COMMIT"'"'$'\n''}' VERSION.json || exit 1

      - name: Install dependencies
        run: bash packages/macos/generate_wazuh_packages.sh -i || exit 1

      - name: Build macOS package
        id: build
        run: |
          REVISION=${{ inputs.revision || '1' }}
          FLAGS="-a ${{ matrix.arch }} -j 2 -r $REVISION --verbose "
          [ "${{ inputs.checksum }}" == "true" ] && FLAGS+="--checksum "
          [ "${{ inputs.debug }}" == "true" ] && FLAGS+="--debug "

          sudo bash packages/macos/generate_wazuh_packages.sh $FLAGS || exit 1

          PACKAGE_NAME=$(find packages/macos/output -maxdepth 1 -type f -name "*agent*.pkg" -exec basename {} \;)
          PACKAGE_SYMBOLS_NAME=$(find packages/macos/output -maxdepth 1 -type f -name "*agent-debug-symbols*.zip" -exec basename {} \;)

          echo "package-name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "package-symbols-name=$PACKAGE_SYMBOLS_NAME" >> $GITHUB_OUTPUT
          echo "version=${{ env.VERSION }}" >> $GITHUB_OUTPUT

  test-macos:
    needs: build-macos
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: intel64
            runner: macos-14-large
          - arch: arm64
            runner: macos-14
    if: always() && needs.build-macos.result == 'success' && (github.event_name == 'pull_request' || inputs.architecture == matrix.arch)
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    name: Test PKG package (${{ matrix.arch }})

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-macos.outputs.package-name }}
          path: packages/macos/output

      - name: Test install macOS package
        run: |
          sudo installer -pkg "packages/macos/output/${{ needs.build-macos.outputs.package-name }}" -target / | sudo tee installer.log
          grep -q "The install was successful" "installer.log" || exit 1

      - name: Checking files after installation
        run: |
          python3 -m venv venv || exit 1
          source venv/bin/activate
          python3 -m pip install -r .github/actions/check_files/requirements.txt || exit 1
          sudo /Library/Ossec/bin/wazuh-control stop || exit 1

          sudo ./venv/bin/python .github/actions/check_files/check_files.py -f ".github/actions/check_files/macos_agent_$(uname -m).csv" --wazuh_gid -1 --wazuh_uid -1 --directory '/Library/Ossec' || exit 1
          sudo ./venv/bin/python .github/actions/check_files/check_files.py -b 'macos_actual_state.csv' --wazuh_gid -1 --wazuh_uid -1 --directory '/Library/Ossec' || exit 1
