run-name: Build Wazuh agent Linux arm64 - ${{ github.event.pull_request.head.ref || github.ref_name }} - ${{ inputs.system || 'deb,rpm' }} - ${{ inputs.architecture || 'arm64' }}
name: 5.X - Build Wazuh agent Linux arm64 (DEB/RPM)

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - "src/**"
      - "packages/**"
      - ".github/workflows/5_builderpackage_agent-linux-arm64.yml"
  workflow_dispatch:
    inputs:
      architecture:
        type: choice
        description: Package architecture [arm64, aarch64].
        required: true
        default: arm64
        options:
          - arm64
          - aarch64
      system:
        type: choice
        description: Package OS [deb, rpm].
        required: true
        default: deb
        options:
          - deb
          - rpm
      revision:
        description: |
          Package revision (name and metadata).
          Default is '0'.
        required: false
        default: "0"
      debug:
        type: boolean
        description: |
          Build the binaries as debug (without optimizations).
          Default is 'false'.
        required: false
        default: false
      checksum:
        type: boolean
        description: |
          Generate package checksum.
          Default is 'false'.
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

env:
  ARCH: arm64

jobs:
  build-package:
    if: github.event_name == 'pull_request' || inputs.system == matrix.system
    runs-on: wz-linux-arm64
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        system: [deb, rpm]
    name: Build ${{ matrix.system }} package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set VERSION and CONTAINER_NAME
        run: |
          VERSION="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' VERSION.json)"
          cat << EOF | sed -e 's/^[[:space:]]*//' -e 's/\r$//' >> $GITHUB_ENV
          VERSION=$VERSION
          TAG=$VERSION
          CONTAINER_NAME=pkg_${{ matrix.system }}_agent_builder_${{ env.ARCH }}
          SYSTEM=${{ matrix.system }}
          EOF

      - name: Download docker image for package building
        run: |
          bash .github/actions/ghcr-pull-and-push/pull_image_from_ghcr.sh ${{ secrets.CI_WAZUH_AGENT_PACKAGES_CLASSIC }} ${{ github.actor}} ${{ env.CONTAINER_NAME }} ${{ env.TAG }}

      - name: Append short commit to VERSION file
        run: |
          SHORT_COMMIT=$(git rev-parse --short=7 HEAD)
          if [ -z "$SHORT_COMMIT" ]; then echo "No commit found"; exit 1; fi
          echo "Found commit: $SHORT_COMMIT"
          sed -i '/"stage":/s/$/,/; /"stage":/a \    "commit": "'"$SHORT_COMMIT"'"' VERSION.json || exit 1
          cat VERSION.json

      - name: Build package
        run: |
          REVISION=${{ inputs.revision || '0' }}
          FLAGS="--verbose -t agent -s /tmp --dont-build-docker -j $(nproc) -r $REVISION "
          if [ "${{ inputs.checksum }}" == "true" ]; then FLAGS+="--checksum "; fi
          if [ "${{ inputs.debug }}" == "true" ]; then FLAGS+="--debug "; fi
          bash packages/generate_package.sh -a ${{ env.ARCH }} --tag ${{ env.TAG }} --system ${{ env.SYSTEM }} $FLAGS

          if [ "${{ matrix.system }}" == "deb" ]; then
            PACKAGE_NAME=$(find /tmp -maxdepth 1 -type f -name "*agent*.deb" -exec basename {} 2>/dev/null \; | grep -v -E "^wazuh-agent-dbg")
            PACKAGE_SYMBOLS_NAME=$(find /tmp -maxdepth 1 -type f -name "*agent*.deb" -exec basename {} 2>/dev/null \; | grep -E "^wazuh-agent-dbg")
          else
            PACKAGE_NAME=$(find /tmp -maxdepth 1 -type f -name "*agent*.rpm" -exec basename {} 2>/dev/null \; | grep -v -E "^wazuh-agent-debuginfo")
            PACKAGE_SYMBOLS_NAME=$(find /tmp -maxdepth 1 -type f -name "*agent*.rpm" -exec basename {} 2>/dev/null \; | grep -E "^wazuh-agent-debuginfo")
          fi

          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "PACKAGE_SYMBOLS_NAME=$PACKAGE_SYMBOLS_NAME" >> $GITHUB_ENV

          cat <<EOF | sed -e 's/^[[:space:]]*//' > /tmp/metadata.env
          PACKAGE_NAME=$PACKAGE_NAME
          PACKAGE_SYMBOLS_NAME=$PACKAGE_SYMBOLS_NAME
          VERSION=${{ env.VERSION }}
          CONTAINER_NAME=${{ env.CONTAINER_NAME }}
          TAG=${{ env.TAG }}
          SYSTEM=${{ matrix.system }}
          EOF

      - name: Upload metadata
        uses: actions/upload-artifact@v4
        with:
          name: metadata-${{ matrix.system }}-arm64
          path: /tmp/metadata.env
          retention-days: 1

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: /tmp/${{ env.PACKAGE_NAME }}
          retention-days: 7

      - name: Upload debug symbols as artifact
        if: env.PACKAGE_SYMBOLS_NAME != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_SYMBOLS_NAME }}
          path: /tmp/${{ env.PACKAGE_SYMBOLS_NAME }}
          retention-days: 7

      - name: Upload checksums as artifacts
        if: inputs.checksum == true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}-checksums
          path: |
            /tmp/${{ env.PACKAGE_NAME }}.sha512
            /tmp/${{ env.PACKAGE_SYMBOLS_NAME }}.sha512
          retention-days: 7

  test-package:
    needs: build-package
    if: github.event_name == 'pull_request' || inputs.system == matrix.system
    runs-on: wz-linux-arm64
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        system: [deb, rpm]
    name: Test ${{ matrix.system }} package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download metadata
        uses: actions/download-artifact@v4
        with:
          name: metadata-${{ matrix.system }}-arm64
          path: /tmp

      - name: Load metadata
        run: |
          tr -d '\r' < /tmp/metadata.env >> $GITHUB_ENV

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: /tmp

      - name: Download docker image for testing
        run: |
          bash .github/actions/ghcr-pull-and-push/pull_image_from_ghcr.sh ${{ secrets.CI_WAZUH_AGENT_PACKAGES_CLASSIC }} ${{ github.actor }} ${{ env.CONTAINER_NAME }} ${{ env.TAG }}

      - name: Test install package
        run: |
          TESTS_PATH=$GITHUB_WORKSPACE/.github/actions/test-install-components/
          if [ -z "${{ env.PACKAGE_NAME }}" ]; then exit 1; fi
          sudo docker run \
            -v $TESTS_PATH/:/tests \
            -v /tmp/:/packages \
            -v /var/ossec:/var/ossec \
            -e ARCH="${{ env.ARCH }}" \
            -e SYSTEM="${{ env.SYSTEM }}" \
            --entrypoint '/tests/install_component.sh' \
            ${{ env.CONTAINER_NAME }}:${{ env.TAG }} \
            ${{ env.PACKAGE_NAME }} agent
          if grep -iq " installed.*wazuh-agent" /tmp/status.log ; then
            echo "Installation successfully."
          else
            exit 1
          fi

      - name: Test uninstall package
        uses: ./.github/actions/5_builderpackage_linux-smoke-uninstall-test
        with:
          tested_docker: "${{ env.CONTAINER_NAME }}:${{ env.TAG }}"

      - name: Get last stable version
        id: last-stable-version
        uses: ./.github/actions/5_builderpackage_get-last-stable-version
        with:
          repo_owner: wazuh
          repo_name: wazuh
          testing_version: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package url of the last stable version
        id: upgrade-package-url
        uses: ./.github/actions/5_builderpackage_get-upgrade-test-package-url
        with:
          component: agent
          os: linux
          system: ${{ env.SYSTEM }}
          version: ${{ steps.last-stable-version.outputs.latest_stable_version }}
          architecture: ${{ env.ARCH }}

      - name: Test upgrade
        uses: ./.github/actions/5_builderpackage_linux-smoke-upgrade-test
        with:
          old_package_url: ${{ steps.upgrade-package-url.outputs.testing_package_url }}
          expected_upgrade_version: ${{ env.VERSION }}
          tested_docker: "${{ env.CONTAINER_NAME }}:${{ env.TAG }}"

  upload-to-s3:
    needs: [build-package, test-package]
    if: success() && (github.event_name == 'pull_request' || inputs.system == matrix.system)
    runs-on: wz-linux-arm64
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        system: [deb, rpm]
    name: Upload ${{ matrix.system }} to S3

    steps:
      - name: Download metadata
        uses: actions/download-artifact@v4
        with:
          name: metadata-${{ matrix.system }}-arm64
          path: /tmp

      - name: Load metadata
        run: |
          tr -d '\r' < /tmp/metadata.env >> $GITHUB_ENV

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: /tmp

      - name: Download debug symbols artifacts
        if: env.PACKAGE_SYMBOLS_NAME != ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_SYMBOLS_NAME }}
          path: /tmp

      - name: Download checksums
        if: inputs.checksum == true
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}-checksums
          path: /tmp

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: ${{ secrets.CI_AWS_REGION }}

      - name: Upload package to S3
        run: |
          S3_URI="s3://xdrsiem-packages-dev-internal/development/wazuh/5.x/main/packages"
          if [ -s "/tmp/${{ env.PACKAGE_NAME }}" ]; then
            aws s3 cp /tmp/${{ env.PACKAGE_NAME }} $S3_URI/
            echo "S3 URI: $S3_URI/${{ env.PACKAGE_NAME }}"
          else
            echo "Package file is empty or does not exist."
            exit 1
          fi

      - name: Upload checksum to S3
        if: inputs.checksum == true
        run: |
          S3_URI="s3://xdrsiem-packages-dev-internal/development/wazuh/5.x/main/packages"
          if [ -s "/tmp/${{ env.PACKAGE_NAME }}.sha512" ]; then
            aws s3 cp /tmp/${{ env.PACKAGE_NAME }}.sha512 $S3_URI/
          else
            echo "Warning: Checksum file not found, skipping"
          fi

      - name: Upload debug symbols to S3
        if: env.PACKAGE_SYMBOLS_NAME != ''
        run: |
          S3_URI="s3://xdrsiem-packages-dev-internal/development/wazuh/5.x/main/packages"
          if [ -s "/tmp/${{ env.PACKAGE_SYMBOLS_NAME }}" ]; then
            aws s3 cp /tmp/${{ env.PACKAGE_SYMBOLS_NAME }} $S3_URI/
          else
            echo "Warning: Debug symbols file not found, skipping"
          fi

      - name: Upload debug symbols checksum to S3
        if: inputs.checksum == true && env.PACKAGE_SYMBOLS_NAME != ''
        run: |
          S3_URI="s3://xdrsiem-packages-dev-internal/development/wazuh/5.x/main/packages"
          if [ -s "/tmp/${{ env.PACKAGE_SYMBOLS_NAME }}.sha512" ]; then
            aws s3 cp /tmp/${{ env.PACKAGE_SYMBOLS_NAME }}.sha512 $S3_URI/
          else
            echo "Warning: Debug symbols checksum file not found, skipping"
          fi
