name: 5 - CodeChecker Docker image - Create and publish

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/testing/codechecker/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wazuh/codechecker

jobs:
  build-and-push-image:
    name: Build and push CodeChecker image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=raw,value=6.27.3-clang20

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: tools/testing/codechecker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
