name: 5.X - Coverity Scan

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project (use ossec-wazuh for development)"
        required: true
        type: choice
        options:
          - wazuh
          - ossec-wazuh
      threads:
        description: "Number of threads for make -j (0 = auto)"
        required: false
        default: 0
        type: number
      docker_image_tag:
        description: |
          Tag name of the Docker image to be uploaded.
          Use only '-', '_', '.' and alphanumeric characters.
          Default is '5.x'.
        required: false
        default: "5.x"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    outputs:
      project: ${{ steps.vars.outputs.PROJECT }}
      version: ${{ steps.vars.outputs.VERSION }}
      description: ${{ steps.vars.outputs.DESCRIPTION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up project and build variables
        id: vars
        run: |
          if [[ "${{ inputs.project }}" == "wazuh" ]]; then
            PROJECT="wazuh/wazuh"
          else
            PROJECT="wazuh/ossec-wazuh"
          fi

          if [[ ${{ inputs.threads }} -le 0 ]]; then
            JOBS=$(nproc)
          else
            JOBS=${{ inputs.threads }}
          fi

          VERSION=$(jq -r '.version + "-" + .stage' VERSION.json)
          DESCRIPTION="Version $VERSION - Git ref ${{ github.ref_name }}"

          cat << EOF | sed -e 's/^[[:space:]]*//' -e 's/\r$//' >> $GITHUB_ENV
          JOBS=$JOBS
          EOF

          cat << EOF | sed -e 's/^[[:space:]]*//' -e 's/\r$//' >> $GITHUB_OUTPUT
          PROJECT=$PROJECT
          VERSION=$VERSION
          DESCRIPTION=$DESCRIPTION
          EOF

      - name: Print variables
        run: |
          echo "Description: ${{ steps.vars.outputs.DESCRIPTION }}"
          echo "Docker Image Tag: ${{ inputs.docker_image_tag }}"

      - name: Download dependencies
        run: make -C src deps -j${{ env.JOBS }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Coverity artifact
        uses: ./.github/actions/coverity/build
        with:
          command: make -C src TARGET=manager COVERITY=YES -j${{ env.JOBS }}
          docker_image_tag: ${{ inputs.docker_image_tag }}

      - name: List files
        run: ls -l cov-int/emit/*/emit-db*

      - name: Archive Coverity build
        run: tar czf wazuh.tgz cov-int

      - name: Upload Coverity artifact
        uses: actions/upload-artifact@v4
        with:
          name: wazuh.tgz
          path: wazuh.tgz
          retention-days: 1

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download Coverity artifact
        uses: actions/download-artifact@v4
        with:
          name: wazuh.tgz

      - name: Upload to Coverity Scan
        uses: ./.github/actions/coverity/upload
        with:
          project: ${{ needs.build.outputs.project }}
          email: ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
          token: ${{ inputs.project == 'wazuh' && secrets.COVERITY_SCAN_WAZUH_TOKEN || secrets.COVERITY_SCAN_OSSEC_TOKEN }}
          version: ${{ needs.build.outputs.version }}
          description: "${{ needs.build.outputs.description }}"
