name: 5.X - FIM on MacOS - Integration tests - Tier 0 and 1

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch"
        required: true
        default: "main"
  pull_request:
    paths:
      - ".github/workflows/5_testintegration_fim-tier-0-1-macos.yml"
      - "src/config/src/syscheck-config.c"
      - "src/config/include/syscheck-config.h"
      - "src/syscheckd/**"
      - "src/Makefile"
      - "tests/integration/conftest.py"
      - "tests/integration/test_fim/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_BASE: ${{ github.base_ref || inputs.base_branch }}
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/.python-version-it"
          architecture: x64
      - name: Build wazuh agent for macOS
        run: |
          make deps -C src TARGET=agent -j2
          make -C src TARGET=agent -j2
      - name: Install wazuh agent for macOS
        run: |
          cat << EOF | sed -e 's/^[[:space:]]*//' > ./etc/preloaded-vars.conf
          USER_LANGUAGE="en"
          USER_INSTALL_TYPE="agent"
          USER_DIR=/Library/Ossec
          USER_ENABLE_SYSCHECK="n"
          USER_ENABLE_ROOTCHECK="n"
          USER_AGENT_MANAGER_IP="127.0.0.1"
          EOF
          sudo sh install.sh
          rm ./etc/preloaded-vars.conf
      - name: Download and install integration tests framework
        run: |
          VERSION="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' VERSION.json)"
          if [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${BRANCH_NAME}`" != "X" ]; then
              QA_BRANCH=${BRANCH_NAME}
          elif [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${BRANCH_BASE}`" != "X" ]; then
              QA_BRANCH=${BRANCH_BASE}
          elif [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${VERSION}`" != "X" ]; then
              QA_BRANCH=${VERSION}
          else
              QA_BRANCH="main"
          fi
          git clone -b ${QA_BRANCH} --single-branch https://github.com/wazuh/qa-integration-framework.git
          sudo pip install qa-integration-framework/
          sudo rm -rf qa-integration-framework/
      - name: Run fim integration tests
        run: |
          cd tests/integration
          sudo GITHUB_SHA="${{ github.sha }}" GITHUB_REF_NAME="${BRANCH_NAME}" python -m pytest --tier 0 --tier 1 test_fim/ --html=results.html --self-contained-html
      # Upload the tests result html as an artifact
      - name: Upload failed test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fim-tier-0-1-macos-test-results-${{ github.run_id }}
          path: ./tests/integration/results.html
          retention-days: 7
