name: 5.X - Syscheck - RTR

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/ci/**"
      - "src/build.py"
      - "src/syscheckd/**"
      - "src/unit_tests/syscheckd/**"
      - "src/Makefile"
      - ".github/workflows/5_testcomponent_syscheck-rtr.yml"
      - ".github/actions/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  rtr:
    strategy:
      fail-fast: false
      matrix:
        module: [syscheckd]
        target: [agent, winagent]
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/install_build_deps
        with:
          target: ${{ matrix.target }}

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/.python-version"
          architecture: x64

      - uses: ./.github/actions/reinstall_cmake

      - name: Run RTR
        run: |
          cd src/ || exit 1
          python build.py --target ${{ matrix.target }} --readytoreview ${{ matrix.module }} || exit 1

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage_report_${{ matrix.target }}
          path: ./**/coverage_report/**
