name: 5.X - Content Manager - Unit tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - ".github/workflows/5_testunit_contentmanager.yml"
      - "src/shared_modules/utils/**"
      - "src/shared_modules/content_manager/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  contentmanager-modules:
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: "false"

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: C++ test pipeline
        uses: ./.github/actions/cpp_test_pipeline
        with:
          target: "content_manager_utest"
          asan: "false"
          with_coverage: "true"
          coverage_path: src/shared_modules/content_manager
          coverage_id: content_manager
          coverage_threshold: "65"

  contentmanager-asan:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: C++ test pipeline (ASAN)
        uses: ./.github/actions/cpp_test_pipeline
        with:
          target: "content_manager_utest"
          asan: "true"
