name: 5.X - Indexer Connector - Unit tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - ".github/workflows/5_testunit_indexerconnector.yml"
      - ".github/actions/cpp_test_pipeline/**"
      - "src/shared_modules/utils/**"
      - "src/shared_modules/indexer_connector/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  indexerconnector-modules:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: C++ test pipeline
        uses: ./.github/actions/cpp_test_pipeline
        with:
          target: "indexer_connector_utest"
          asan: "false"
          with_coverage: "true"
          coverage_path: src/shared_modules/indexer_connector
          coverage_id: indexer_connector
          validate_function_coverage: "false"

  indexerconnector-asan:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: C++ test pipeline (ASAN)
        uses: ./.github/actions/cpp_test_pipeline
        with:
          target: "indexer_connector_utest"
          asan: "true"
