name: 5_testunit_shared_modules_file_helper

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/5_testunit_shared_modules_file_helper.yml"
      - "src/shared_modules/file_helper/**"

jobs:
  shared_modules_file_helper-modules:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/build_external_deps

      - name: Shared modules file_helper - Build filesystem tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "filesystem_unit_test"
          test: "true"
          asan: "false"

      - name: Shared modules file_helper - Build file_io tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "file_io_unit_test"
          test: "true"
          asan: "false"

      - name: Shared modules file_helper - Run tests
        uses: ./.github/actions/test_cpp
        with:
          valgrind: "true"
          target: "file_helper_utest"

      - name: Shared modules file_helper - Coverage
        uses: ./.github/actions/coverage_cpp
        with:
          path: src/shared_modules/file_helper
          id: file_helper_utest
          threshold: "60"
          validate_function_coverage: "false"

  shared_modules_file_helper-asan:
    strategy:
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/build_external_deps

      - name: Shared modules file_helper - Build filesystem tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "filesystem_unit_test"
          test: "true"
          asan: "true"

      - name: Shared modules file_helper - Build file_io tests
        uses: ./.github/actions/build_target_cpp
        with:
          target: "file_io_unit_test"
          test: "true"
          asan: "true"

      - name: Shared modules file_helper - Run tests
        uses: ./.github/actions/test_cpp
        with:
          target: "file_helper_utest"
          valgrind: "false"
