name: 5.X - Router - Unit tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - ".github/workflows/5_testunit_router.yml"
      - ".github/actions/cpp_test_pipeline/**"
      - "src/shared_modules/utils/**"
      - "src/shared_modules/router/**"
      - ".github/actions/build_external_deps/**"
      - ".github/actions/build_target_cpp/**"
      - ".github/actions/coverage_cpp/**"
      - ".github/actions/test_cpp/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  router-modules:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: C++ test pipeline
        uses: ./.github/actions/cpp_test_pipeline
        with:
          target: "librouter_utest"
          asan: "false"
          with_coverage: "true"
          coverage_path: src/shared_modules/router
          coverage_id: router
          validate_function_coverage: "false"

  router-asan:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: C++ test pipeline (ASAN)
        uses: ./.github/actions/cpp_test_pipeline
        with:
          target: "librouter_utest"
          asan: "true"
