name: 5.X - RBAC (Framework) - Integration tests - Tier 0 and 1

on:
  pull_request:
    paths:
      - ".github/workflows/5_testintegration_rbac-tier-0-1.yml"
      - "framework/wazuh/rbac/"
      - "src/Makefile"
      - "tests/integration/conftest.py"
      - "tests/integration/test_api/test_rbac/**"
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch"
        required: true
        default: "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_BASE: ${{ github.base_ref || inputs.base_branch }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version-it"
          architecture: x64
      - name: "Install a compatible CMake"
        uses: ./.github/actions/reinstall_cmake
      - name: Build wazuh manager for linux
        run: |
          make deps -C src TARGET=manager -j2
          make -C src TARGET=manager -j2

          sudo mkdir -p /var/wazuh-manager/etc/certs
          sudo touch /var/wazuh-manager/etc/certs/root-ca.pem
          sudo touch /var/wazuh-manager/etc/certs/manager.pem
          sudo touch /var/wazuh-manager/etc/certs/manager-key.pem
      - name: Install wazuh manager for linux
        run: |
          cat << EOF | sed -e 's/^[[:space:]]*//' > ./etc/preloaded-vars.conf
          USER_LANGUAGE="en"
          USER_INSTALL_TYPE="manager"
          USER_DIR=/var/wazuh-manager
          USER_ENABLE_EMAIL="n"
          USER_ENABLE_SYSCHECK="n"
          USER_ENABLE_ROOTCHECK="n"
          USER_ENABLE_SYSCOLLECTOR="n"
          USER_ENABLE_SCA="n"
          USER_ENABLE_AUTHD="n"
          USER_AUTO_START="y"
          EOF
          sudo sh install.sh
          rm ./etc/preloaded-vars.conf

      - name: Download and install integration tests framework
        run: |
          VERSION="$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' VERSION.json)"
          if [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${BRANCH_NAME}`" != "X" ]; then
              QA_BRANCH=${BRANCH_NAME}
          elif [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${BRANCH_BASE}`" != "X" ]; then
              QA_BRANCH=${BRANCH_BASE}
          elif [ "X`git ls-remote https://github.com/wazuh/qa-integration-framework.git ${VERSION}`" != "X" ]; then
              QA_BRANCH=${VERSION}
          else
              QA_BRANCH="main"
          fi
          git clone -b ${QA_BRANCH} --single-branch https://github.com/wazuh/qa-integration-framework.git
          sudo pip install qa-integration-framework/
          sudo rm -rf qa-integration-framework/
      # Run integration tests.
      - name: Run API tests
        run: |
          mkdir -p /tmp/wazuh-logs
          sudo tail -F /var/wazuh-manager/logs/api.log >> /tmp/wazuh-logs/api.log 2>/dev/null &
          sudo tail -F /var/wazuh-manager/logs/wazuh-manager.log >> /tmp/wazuh-logs/wazuh-manager.log 2>/dev/null &
          cd tests/integration
          sudo GITHUB_SHA="${{ github.sha }}" GITHUB_REF_NAME="${BRANCH_NAME}" python -m pytest test_api/test_rbac/ --tier 0 --tier 1 --html=results.html --self-contained-html
      # Collect logs if tests fail
      - name: Collect logs on failure
        if: failure()
        run: |
          sudo journalctl -u wazuh-manager > /tmp/wazuh-logs/wazuh-manager.service.log || true
          sudo chown -R $(whoami):$(whoami) /tmp/wazuh-logs || true
      # Upload logs artifact if test fails
      - name: Upload logs artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: wazuh-logs-${{ github.job }}
          path: /tmp/wazuh-logs
      # Upload the tests result html as an artifact
      - name: Upload failed test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: rbac-tier-0-1-test-results-${{ github.run_id }}
          path: ./tests/integration/results.html
          retention-days: 7
