name: 5.X - Router - Component tests

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - ".github/workflows/5_testcomponent_router.yml"
      - "src/shared_modules/utils/**"
      - "src/shared_modules/router/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  router-tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - test_type: valgrind
            asan_enabled: "false"
            valgrind_enabled: "true"
          - test_type: asan
            asan_enabled: "true"
            valgrind_enabled: "false"
    name: Run tests (${{ matrix.test_type }})

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/build_external_deps

      - uses: ./.github/actions/build_target_cpp
        with:
          target: "librouter_ctest"
          test: "true"
          asan: ${{ matrix.asan_enabled }}

      - uses: ./.github/actions/test_cpp
        with:
          target: "librouter_ctest"
          valgrind: ${{ matrix.valgrind_enabled }}
