name: 5.X - FIM on Windows - Integration tests - Tier 0 and 1

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch'
        required: true
        default: 'main'
      head_sha:
        description: 'PR head SHA to download artifacts'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  # Execute the tests on windows.
  run-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - shard_name: tier-0
            pytest_tier_args: "--tier 0"
          - shard_name: tier-1
            pytest_tier_args: "--tier 1"
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_BASE: ${{ github.base_ref || inputs.base_branch }}
      BUILD_WORKFLOW: 5_builderpackage_agent-windows.yml
      AGENT_PACKAGE_REGEXP: wazuh-agent.*windows.*\.msi
      PR_HEAD_SHA: ${{ inputs.head_sha || github.event.pull_request.head.sha || github.sha }}
    runs-on: windows-2025
    name: Run FIM integration tests (${{ matrix.shard_name }})
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PR_HEAD_SHA }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version-it"
          architecture: x64
      - name: Download MSI package artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ${{ env.BUILD_WORKFLOW }}
          commit: ${{ env.PR_HEAD_SHA }}
          name_is_regexp: true
          name: ${{ env.AGENT_PACKAGE_REGEXP }}
          path: C:\wazuh-package\
          if_no_artifact_found: fail
          check_artifacts: true
          search_artifacts: true
      # Install the windows agent.
      - name: Install wazuh agent
        shell: pwsh
        run: |
          $package = Get-ChildItem -Path "C:\wazuh-package" -Filter "wazuh-agent*windows*.msi" -File -Recurse | Where-Object { $_.Name -notmatch 'debug' } | Select-Object -First 1
          if (-not $package) {
            Write-Host "ERROR: No MSI package found in C:\wazuh-package"
            Get-ChildItem -Path "C:\wazuh-package" -Recurse | Format-Table Name, FullName
            exit 1
          }

          Start-Process msiexec.exe -ArgumentList "/i `"$($package.FullName)`" /q WAZUH_MANAGER=`"127.0.0.1`"" -Wait -NoNewWindow
      # Download and install integration tests framework.
      - name: Download and install qa-integration-framework
        shell: pwsh
        run: |
          # Read version from VERSION.json
          $VERSION = (Get-Content -Raw VERSION.json | ConvertFrom-Json).version
          if (git ls-remote https://github.com/wazuh/qa-integration-framework.git $env:BRANCH_NAME) {
              $QA_BRANCH = $env:BRANCH_NAME
          } elseif (git ls-remote https://github.com/wazuh/qa-integration-framework.git $env:BRANCH_BASE) {
              $QA_BRANCH = $env:BRANCH_BASE
          } elseif (git ls-remote https://github.com/wazuh/qa-integration-framework.git $VERSION) {
              $QA_BRANCH = $VERSION
          } else {
              $QA_BRANCH = "main"
          }
          git clone -b $QA_BRANCH --single-branch https://github.com/wazuh/qa-integration-framework.git
          pip install qa-integration-framework/
          Remove-Item qa-integration-framework -Recurse -Force
      - name: Copy integration tests to C:\wazuh
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path C:\wazuh\tests | Out-Null
          Copy-Item -Path "$env:GITHUB_WORKSPACE\tests\*" -Destination C:\wazuh\tests -Recurse -Force
      # Run fim integration tests.
      - name: Run fim integration tests
        run: |
          NET START wazuh
          cd C:\wazuh\tests\integration
          $env:GITHUB_SHA="${{ github.sha }}"; $env:GITHUB_REF_NAME="$env:BRANCH_NAME"; python -m pytest ${{ matrix.pytest_tier_args }} test_fim\ --html=results.html --self-contained-html
      # Upload the tests result html as an artifact
      - name: Upload failed test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fim-tier-0-1-win-${{ matrix.shard_name }}-test-results-${{ github.run_id }}
          path: C:\wazuh\tests\integration\results.html
          retention-days: 7
