name: 5.X - macOS compilation test

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - "src/**"
      - ".github/workflows/5_testcomponent_build-macos.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sonoma:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: macos-15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build wazuh agent for macOS 14
        run: |
          make deps -C src TARGET=agent -j3
          make -C src TARGET=agent -j3
