name: 5.X - Inventory Sync - Unit tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - ".github/workflows/5_testunit_inventorysync.yml"
      - "src/shared_modules/utils/**"
      - "src/wazuh_modules/inventory_sync/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  inventorysync-modules:
    runs-on: ubuntu-24.04
    steps:
      - name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: "true"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: "false"

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: C++ test pipeline
        uses: ./.github/actions/cpp_test_pipeline
        with:
          target: "inventory_sync_utest"
          asan: "false"
          with_coverage: "true"
          coverage_path: src/wazuh_modules/inventory_sync
          coverage_id: inventory_sync
          validate_function_coverage: "false"

  inventorysync-asan:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: C++ test pipeline (ASAN)
        uses: ./.github/actions/cpp_test_pipeline
        with:
          target: "inventory_sync_utest"
          asan: "true"
