name: 5.X - Indexer Connector - Component tests

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - ".github/workflows/5_testcomponent_indexer-connector.yml"
      - "src/shared_modules/indexer_connector/**"
      - "src/shared_modules/utils/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  indexer-connector-tests:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.draft }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        include:
          - test_type: valgrind
            asan_enabled: "false"
            valgrind_enabled: "true"
          - test_type: asan
            asan_enabled: "true"
            valgrind_enabled: "false"
    name: Run tests (${{ matrix.test_type }})

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compatible CMake
        uses: ./.github/actions/reinstall_cmake

      - name: Build external dependencies
        uses: ./.github/actions/build_external_deps

      - name: Indexer Connector - Build tests
        uses: ./.github/actions/build_target_cpp
        with:
          test: "true"
          asan: "${{ matrix.asan_enabled }}"
          target: "indexer_connector_ctests"

      - name: Indexer Connector - Run tests
        uses: ./.github/actions/test_cpp
        with:
          valgrind: "${{ matrix.valgrind_enabled }}"
          target: "indexer_connector_ctests"
