name: 5.X - Running RTR. Module schema_validator for agent/winagent targets

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - "src/ci/**"
      - "src/build.py"
      - "src/shared_modules/schema_validator/**"
      - ".github/workflows/5_testcomponent_schema_validator-rtr.yml"
      - ".github/actions/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  rtr:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    strategy:
      fail-fast: false
      matrix:
        module: [shared_modules/schema_validator]
        target: [agent, winagent]
    runs-on: codebuild-github-actions-codebuild-runner-server-amd-${{ github.run_id }}-${{ github.run_attempt }}
    timeout-minutes: 60
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: "Install dependencies"
        uses: ./.github/actions/install_build_deps
        with:
          target: ${{ matrix.target }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version"
          architecture: x64
      - name: "Install a compatible CMake"
        uses: ./.github/actions/reinstall_cmake
      - name: Run RTR for module ${{ matrix.module }} and target ${{ matrix.target }}
        run: |
          cd src/
          python build.py --target ${{ matrix.target }} --readytoreview ${{ matrix.module }}
      - name: Uploading coverage report
        if: always()
        uses: ./.github/actions/upload_s3_artifact
        with:
          aws_region: ${{ secrets.CI_AWS_REGION }}
          bucket: ${{ secrets.CI_INTERNAL_S3_BUCKET }}
          aws_role: ${{ secrets.CI_OIDC_ROLE_ARN }}
          name: coverage_report ${{ matrix.target }}
          path: ./**/coverage_report/**
