name: 5.X - Syscollector on Linux - Integration tests - Tier 0 and 1

on:
  pull_request:
    paths:
      - ".github/workflows/5_testintegration_syscollector-tier-0-1-lin.yml"
      - "src/config/src/wmodules-syscollector.c"
      - "src/wazuh_modules/syscollector/**"
      - "src/Makefile"
      - "tests/integration/conftest.py"
      - "tests/integration/test_syscollector/**"
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch"
        required: true
        default: "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_BASE: ${{ github.base_ref || inputs.base_branch }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".github/workflows/.python-version-it"
          architecture: x64
      - name: Install a compatible CMake
        uses: ./.github/actions/reinstall_cmake
      - name: Build wazuh agent
        uses: ./.github/actions/build_wazuh
        with:
          target: agent
      - name: Install wazuh agent for linux
        uses: ./.github/actions/install_wazuh_agent
        with:
          disable_sca_syscollector: "true"
      - name: Install QA integration framework
        uses: ./.github/actions/install_qa_framework
        with:
          branch_name: ${{ env.BRANCH_NAME }}
          branch_base: ${{ env.BRANCH_BASE }}
      - name: Run syscollector integration tests
        run: |
          cd tests/integration
          sudo GITHUB_SHA="${{ github.sha }}" GITHUB_REF_NAME="${{ env.BRANCH_NAME }}" python -m pytest --tier 0 --tier 1 test_syscollector/ --html=results.html --self-contained-html
      - name: Upload failed test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: syscollector-test-results-${{ github.run_id }}
          path: ./tests/integration/results.html
          retention-days: 7
