name: Integration tests for API - Tier 0 and 1

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch'
        required: true
        default: 'main'
  pull_request:
    paths:
      - ".github/workflows/integration-tests-api-tier-0-1.yml"
      - "api/**"
      - "src/Makefile"
      - "tests/integration/conftest.py"
      - "tests/integration/test_api/**"
      - "!tests/integration/test_api/test_rbac/**"

jobs:
  build:
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      BRANCH_BASE: ${{ github.base_ref || inputs.base_branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/.python-version-it"
          architecture: x64
      # Install wazuh server for linux.
      - name: Install wazuh server for linux
        run: |
          echo 'VCPKG_ROOT="/usr/local/share/vcpkg"' >> ./etc/preloaded-vars.conf
          echo 'USER_LANGUAGE="en"' >> ./etc/preloaded-vars.conf
          echo 'USER_NO_STOP="y"' >> ./etc/preloaded-vars.conf
          echo 'USER_DELETE_DIR="y"' >> ./etc/preloaded-vars.conf
          echo 'USER_UPDATE="n"' >> ./etc/preloaded-vars.conf
          echo 'USER_ENABLE_EMAIL="n"' >> ./etc/preloaded-vars.conf
          echo 'USER_WHITE_LIST="n"' >> ./etc/preloaded-vars.conf
          echo 'USER_ENABLE_SYSLOG="y"' >> ./etc/preloaded-vars.conf
          echo 'USER_ENABLE_AUTHD="y"' >> ./etc/preloaded-vars.conf
          echo 'USER_SERVER_IP="MANAGER_IP"' >> ./etc/preloaded-vars.conf
          echo 'USER_CA_STORE="/path/to/my_cert.pem"' >> ./etc/preloaded-vars.conf
          echo 'USER_GENERATE_AUTHD_CERT="y"' >> ./etc/preloaded-vars.conf
          echo 'USER_AUTO_START="n"' >> ./etc/preloaded-vars.conf
          echo 'USER_CREATE_SSL_CERT="n"' >> ./etc/preloaded-vars.conf
          echo 'DOWNLOAD_CONTENT="y"' >> ./etc/preloaded-vars.conf
          export VCPKG_ROOT="/usr/local/share/vcpkg"
          sudo ./install.sh
          rm ./etc/preloaded-vars.conf

