name: Package - Upload Wazuh Server Latest

on:
  push:
    branches:
    # - '[0-9]+.[0-9]+.[0-9]+'
    # - 'main'
    - 'enhancement/28404-add-latest-package'
  workflow_run:
    workflows: ["Build Wazuh server"]
    types:
      - completed
  workflow_dispatch:

jobs:
  create-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Download latest built package
        uses: actions/download-artifact@v4
        with:
          path: /tmp/

      - name: Find the package name
        run: |
          PACKAGE_NAME=$(ls -t /tmp | grep -E 'wazuh-server_.*\.(deb|rpm)' | head -n 1)
          LATEST_PACKAGE_NAME=$(echo $PACKAGE_NAME | sed 's/[a-f0-9]\{7,\}/latest/')
          cp /tmp/$PACKAGE_NAME /tmp/$LATEST_PACKAGE_NAME
          echo "LATEST_PACKAGE_NAME=$LATEST_PACKAGE_NAME" >> $GITHUB_ENV
          
      - name: Upload latest package to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LATEST_PACKAGE_NAME }}
          path: /tmp/${{ env.LATEST_PACKAGE_NAME }}
          if-no-files-found: error
          
      - name: Upload latest package to S3
        run: |
          aws s3 cp /tmp/${{ env.LATEST_PACKAGE_NAME }} s3://packages-dev.internal.wazuh.com/development/wazuh/5.x/main/packages/
          s3uri="s3://packages-dev.internal.wazuh.com/development/wazuh/5.x/main/packages/${{ env.LATEST_PACKAGE_NAME }}"
          echo "S3 latest package URI: ${s3uri}"

      - name: Upload latest checksum to S3
        run: |
          aws s3 cp /tmp/${{ env.LATEST_PACKAGE_NAME }}.sha512 s3://packages-dev.internal.wazuh.com/development/wazuh/5.x/main/packages/
          s3uri="s3://packages-dev.internal.wazuh.com/development/wazuh/5.x/main/packages/${{ env.LATEST_PACKAGE_NAME }}.sha512"
          echo "S3 latest checksum URI: ${s3uri}"
